### ISSUE TITLE
关于ae奇点的合成

### ISSUE THREAD

**Issue by 0Yimeng0** [ET-Team/EnigTech2#119]
ae奇点的合成是十分便宜的，因为ae的物质聚合器接受流体。
以这个包为例，我只需要用幻灵流体接口链接水槽并开启自动输出对聚合器供水,即能在1s内做出20+奇点。(这以前是有个视频的，只不过该视频up主忆尘已将自身所有mc视频删除，包括我所说视频。)

如果不是故意设置，是否考虑将所有涉及ae奇点的合成修改?

**Comment by dong031001** [comment]
同意，应禁用流体参与奇点合成
