### ISSUE TITLE
[BUG]德鲁伊宝典进度无法获得

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#125]
**描述BUG**
德鲁伊宝典进度无法获得
**如何重现**
在1.2.3版本中尝试制作德鲁伊宝典
**原本期望**
若无此BUG，原本你期待发生什么？
获得该成就
**截图**
![1](https://user-images.githubusercontent.com/11871061/70802580-cacad800-1dec-11ea-959f-3a2be5cb8f9c.png)
![2](https://user-images.githubusercontent.com/11871061/70802583-ce5e5f00-1dec-11ea-8199-ba1f4b44ccac.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.2.3

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
无法重现
