### ISSUE TITLE
炼油气无法蒸馏[BUG]

### ISSUE THREAD

**Issue by 0-bingci** [ET-Team/EnigTech2#128]
**描述BUG**
炼油气无法装进简易蒸馏机里
**如何重现**
炼油气桶无法右键放进去
**原本期望**
若无此BUG，原本你期待发生什么？
产出液态乙烯
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
在1.2.4版本已经修复

**Comment by dong031001** [comment]
#116
