### ISSUE TITLE
[BUG]“魔力激发器”无法使用

### ISSUE THREAD

**Issue by JerryS116** [ET-Team/EnigTech2#131]
**原因分析**
配置文件中对多方块结构“魔力激发器”的注册名为"mana_extractor"，而合成表脚本中使用的名称为"magic_extractor"，将后者改为mana_extractor即可修复（已提交PR）
**描述BUG**
多方块结构“魔力激发器”无法使用（放入正常输入物品不工作）
**如何重现**
搭建多方块结构“魔力激发器”并放入正常输入物品（灰烬水晶簇）
**原本期望**
消耗灰烬水晶簇并产生魔力
**截图**
![图片](https://user-images.githubusercontent.com/43673838/70848814-d502da00-1eb1-11ea-8b09-11a2a87ac2a9.png)

**运行环境（请越详细越好）:**
 - 操作系统：Windows 10
 - 运行内存：6GB
 - Java版本：无关
- 整合包版本：1.2.3（1.2.4的脚本未修复）

**Comment by dong031001** [comment]
#133
