### ISSUE TITLE
[BUG]魔力激发器找不到配方

### ISSUE THREAD

**Issue by 0-bingci** [ET-Team/EnigTech2#136]
**描述BUG**
灰烬水晶簇放进去没有效果
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
产生大量魔力
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
#131 重复Issue
