### ISSUE TITLE
[BUG]1.2.4-Release 使用升级包升级版本后，流体蒸馏器与流体成型机无相关使用配方

### ISSUE THREAD

**Issue by alkkhsl** [ET-Team/EnigTech2#137]
重新下载完整1.2.4客户端已解决问题。

问题出在1.2.4升级包，并未加入流体蒸馏器及流体成型机的有关合成配方。

**Comment by alkkhsl** [comment]
专家模式

**Comment by dong031001** [comment]
无法重现，检查了升级包内文件，确有对应配方添加

**Comment by alkkhsl** [comment]
> 无法重现，检查了升级包内文件，确有对应配方添加

重新描述：在1.2.2版本直接覆盖1.2.4patch升级，无法看到炼油气合成聚乙烯及所有使用流体蒸馏器与流体成型机的配方，此两台机器配方正常可见。

**Comment by dong031001** [comment]
请提供游玩时使用的模组

> > 无法重现，检查了升级包内文件，确有对应配方添加
> 
> 重新描述：在1.2.2版本直接覆盖1.2.4patch升级，无法看到炼油气合成聚乙烯及所有使用流体蒸馏器与流体成型机的配方，此两台机器配方正常可见。

**Comment by alkkhsl** [comment]
专家模式

**Comment by alkkhsl** [comment]
> 请提供游玩时使用的模式
> 
> > > 无法重现，检查了升级包内文件，确有对应配方添加
> > 
> > 
> > 重新描述：在1.2.2版本直接覆盖1.2.4patch升级，无法看到炼油气合成聚乙烯及所有使用流体蒸馏器与流体成型机的配方，此两台机器配方正常可见。

专家模式

**Comment by dong031001** [comment]
> > 请提供游玩时使用的模式
> > > > 无法重现，检查了升级包内文件，确有对应配方添加
> > > 
> > > 
> > > 重新描述：在1.2.2版本直接覆盖1.2.4patch升级，无法看到炼油气合成聚乙烯及所有使用流体蒸馏器与流体成型机的配方，此两台机器配方正常可见。
> 
> 专家模式

确认问题为1.2.3更新中统一了专家模式和普通模式脚本文件导致1.2.2升级1.2.4产生了冗余的专家模式脚本，感谢汇报，将会在下个版本中以一个空文件替换
