### ISSUE TITLE
[BUG]余烬激光蚀刻机无法成型

### ISSUE THREAD

**Issue by alkkhsl** [ET-Team/EnigTech2#141]
1.2.4版本专家模式
反复搭建模块化机械中的余烬激光蚀刻机（包括尝试使用充电的物品展示台与充能的光束炮）
均提示结构不完整，无法成型。

**Comment by dong031001** [comment]
问题之前出现过，是激光炮摆放方向问题，需对准物品展示台

**Comment by alkkhsl** [comment]
> 问题之前出现过，是激光炮摆放方向问题，需对准物品展示台

![image](https://user-images.githubusercontent.com/40649667/70879415-333dd300-2000-11ea-9413-14309aecef81.png)
尝试过激光炮的各种方向，依然无法成型。

**Comment by dong031001** [comment]
@ChromaPIE @tuna5544 你们俩测试一下，我现在有点忙

**Comment by ljttty** [comment]
![光束炮代码](https://user-images.githubusercontent.com/45281747/70881760-929fe100-2008-11ea-877a-a115a9c297dc.png)
这是我找到的多方块中唯一奇怪的地方，为什么是@2,1.2.4单机专家难度测试无法成型。

**Comment by dong031001** [comment]
> ![光束炮代码](https://user-images.githubusercontent.com/45281747/70881760-929fe100-2008-11ea-877a-a115a9c297dc.png)
> 这是我找到的多方块中唯一奇怪的地方，为什么是@2,1.2.4单机专家难度测试无法成型。

metadata值为2

**Comment by ljttty** [comment]
> > ![光束炮代码](https://user-images.githubusercontent.com/45281747/70881760-929fe100-2008-11ea-877a-a115a9c297dc.png)
> > 这是我找到的多方块中唯一奇怪的地方，为什么是@2,1.2.4单机专家难度测试无法成型。
> 
> metadata值为2

光束炮的元数据游戏里显示不是0吗，不太懂这些

**Comment by dong031001** [comment]
> > > ![光束炮代码](https://user-images.githubusercontent.com/45281747/70881760-929fe100-2008-11ea-877a-a115a9c297dc.png)
> > > 这是我找到的多方块中唯一奇怪的地方，为什么是@2,1.2.4单机专家难度测试无法成型。
> > 
> > 
> > metadata值为2
> 
> 光束炮的元数据游戏里显示不是0吗，不太懂这些

放置出来之后可以拥有不同的metadata来表示不同朝向

**Comment by ljttty** [comment]
> > > > ![光束炮代码](https://user-images.githubusercontent.com/45281747/70881760-929fe100-2008-11ea-877a-a115a9c297dc.png)
> > > > 这是我找到的多方块中唯一奇怪的地方，为什么是@2,1.2.4单机专家难度测试无法成型。
> > > 
> > > 
> > > metadata值为2
> > 
> > 
> > 光束炮的元数据游戏里显示不是0吗，不太懂这些
> 
> 放置出来之后可以拥有不同的metadata来表示不同朝向

谢谢的你解答，现在才知道还有这种事

**Comment by dong031001** [comment]
![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
测试搭建无问题

**Comment by ljttty** [comment]
> ![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
> 测试搭建无问题

能看看你用的所用方块表和机器的朝向吗？

**Comment by dong031001** [comment]
> > ![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
> > 测试搭建无问题
> 
> 能看看你用的所用方块表和机器的朝向吗？

小型物品输入/输出端口，大型余烬输入端口，琥珀金板块，光束炮，物品展示台（均未充能），机械控制器
控制器面朝正北

**Comment by alkkhsl** [comment]
> > > ![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
> > > 测试搭建无问题
> > 
> > 
> > 能看看你用的所用方块表和机器的朝向吗？
> 
> 小型物品输入/输出端口，大型余烬输入端口，琥珀金板块，光束炮，物品展示台（均未充能），机械控制器，因瓦合金块
> 控制器面朝正北

1.2.4单机测试成功，仅控制器面向北侧结构成型，其余朝向均无法成型。谢谢及时解决！

**Comment by dong031001** [comment]
> > > > ![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
> > > > 测试搭建无问题
> > > 
> > > 
> > > 能看看你用的所用方块表和机器的朝向吗？
> > 
> > 
> > 小型物品输入/输出端口，大型余烬输入端口，琥珀金板块，光束炮，物品展示台（均未充能），机械控制器，因瓦合金块
> > 控制器面朝正北
> 
> 1.2.4单机测试成功，仅控制器面向北侧结构成型，其余朝向均无法成型。谢谢及时解决！

怀疑问题确是由metadata值引起，应让光束炮指向正北时其metadata值才为2，使得机器成型

**Comment by alkkhsl** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/30747164/70882978-1ae59e00-1f97-11ea-8e7a-0178d4aa7a52.png)
> > > > > 测试搭建无问题
> > > > 
> > > > 
> > > > 能看看你用的所用方块表和机器的朝向吗？
> > > 
> > > 
> > > 小型物品输入/输出端口，大型余烬输入端口，琥珀金板块，光束炮，物品展示台（均未充能），机械控制器，因瓦合金块
> > > 控制器面朝正北
> > 
> > 
> > 1.2.4单机测试成功，仅控制器面向北侧结构成型，其余朝向均无法成型。谢谢及时解决！
> 
> 怀疑问题确是由metadata值引起，因光束炮指向正北时其metadata值才为2，使得机器成型，其余朝向都无效

问题已验证，单机测试无论机器朝向何方，只要将光束炮指向正北均可成型。收获良多，谢谢！

**Comment by dong031001** [comment]
Note to self: 制作带有朝向方块（如光束炮，原木，火把，etc）模块化机器时应在自动导出结构文件后检查metadata以避免无法搭建非初始方向机器。 @dong031001
