### ISSUE TITLE
[BUG]加载光影后物品渲染出错闪退

### ISSUE THREAD

**Issue by Yukino-Sistine** [ET-Team/EnigTech2#146]
**描述BUG**
关闭光影后问号物品渲染出错，再加载光影进入世界后闪退。
**如何重现**
同上，光影有关（附崩溃日志）。
**原本期望**
若无此BUG，原本你期待发生什么？
正常玩耍（我才刚开始，阶段一）。
**截图**
昨晚几次闪退（图一）：
![16162338](https://user-images.githubusercontent.com/58933029/70890631-7f007480-2020-11ea-86e4-57bea489d862.jpg)
今天进阶后的闪退（图二）：
![image](https://user-images.githubusercontent.com/58933029/70890079-2086c680-201f-11ea-855c-0bec7e5d1e84.png)
关闭光影后物品栏（图三）:
![image](https://user-images.githubusercontent.com/58933029/70890296-a73ba380-201f-11ea-9379-3fea322c1dd2.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：16G
 - Java版本：1.8？
- 整合包版本*：1.24

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

[crash-reports.zip](https://github.com/ET-Team/EnigTech2/files/3966738/crash-reports.zip)

**Comment by ChromaPIE** [comment]
似非整合包问题。尝试关闭你的光影

**Comment by Yukino-Sistine** [comment]
> 似非整合包问题。尝试关闭你的光影

我把问题物品烧毁后闪退问题解决了。
