### ISSUE TITLE
[BUG]高级火箭 氧气和氢气没给合成

### ISSUE THREAD

**Issue by alkkhsl** [ET-Team/EnigTech2#169]
版本1.2.7 专家模式
P5阶段末期，上月球需要太空服及氧气罐，然而看JEI发现高级火箭自身的氧气与氢气被删除，能看到mek的氧气桶，而mek的氧气需要在P6才能解锁。无法上月球就无法解锁P6。
![QQ图片20191218201457](https://user-images.githubusercontent.com/40649667/71085888-7b611f00-21d3-11ea-86a8-8e311ea28467.png)
![YY图片20191218201509](https://user-images.githubusercontent.com/40649667/71085901-80be6980-21d3-11ea-84f4-5f78eadeec15.jpg)

**Comment by dong031001** [comment]
#168
