### ISSUE TITLE
[BUG] P5中的天使指环在P5阶段其实并做不出来。

### ISSUE THREAD

**Issue by alkkhsl** [ET-Team/EnigTech2#173]
P5进度末期天使指环中
红石推进器 need->荧石推进单元 need-> 流明锭

而流明锭唯一合成方式在P6解锁，为P6中期核电工艺模组流体注入器合成。

So建议：更改天使指环进度至P6，or P5阶段添加流明锭合成方式。

**Comment by dong031001** [comment]
@tuna5544 迁移进度至阶段六
