### ISSUE TITLE
[BUG]氯化机等机器流体传输问题

### ISSUE THREAD

**Issue by Control-Core** [ET-Team/EnigTech2#175]
**描述BUG**
氯化机无法使用桶进行输出，并且EnderIO的末影液体导管也无法进行输入输出，如果改用EnderIO的高压液体导管或者Embers的流体泵进行抽取的话会优先抽取左侧储罐的氯化氢流体，输入则正常，简易流体蒸馏器除了无法用桶输出外其余情况正常
**如何重现**
正常使用氯化机
**原本期望**
若无此BUG，原本你期待发生什么？
正常使用
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by alkkhsl** [comment]
简易流体蒸馏器无法用管道输入

**Comment by dong031001** [comment]
尝试过使用末影液体导管的白名单功能进行输出吗？

**Comment by dong031001** [comment]
EXU2作者弃坑，转为特性
