### ISSUE TITLE
[BUG] 流明锭没有烧炼配方

### ISSUE THREAD

**Issue by ljttty** [ET-Team/EnigTech2#179]
**描述BUG**
在最新的 1.2.8专家模式中，锡银合金没有合成表

**截图**
![image](https://user-images.githubusercontent.com/45281747/71183282-ae2e1480-22b2-11ea-9991-2050c623ba40.png)

**Comment by ChromaPIE** [comment]
除此之外，**铅铂合金**、**朦胧银合金**、**锆合金**亦无合成表，且经验证**普通模式下亦无合成表**。
直接导致**末影锭**（需铅铂合金）、**信素锭**（需朦胧银合金）、**熔盐裂变容器**（锆合金）、**流明锭**（锡银合金）**无法合成**。

@dong031001 @tuna5544 尽快定夺魔能高炉或合金炉配方

**Comment by dong031001** [comment]
在 #181 中修复
