### ISSUE TITLE
[BUG]炼油厂输出随机问题&液体漏斗导致崩溃

### ISSUE THREAD

**Issue by JerryS116** [ET-Team/EnigTech2#192]
**描述BUG**
1.炼油厂产物输出到三个输出口时是随机的，对单独的流体处理方案较不友好；
2.炼油厂输出口-流体漏斗-ExU2铁桶的方案时，由于输出随机需要挖开铁桶，此时流体漏斗会自动将液体放置到世界中，用桶（原版）盛起液体（炼油气）后右击装有炼油气的ExU2铁桶时游戏崩溃
**如何重现**
如描述中所说；1可直接搭建并正常使用炼油厂时重现，2未复现成功
**原本期望**
若无此BUG，原本你期待发生什么？
1.炼油厂的三个输出方块最好能固定输出三种产物；
2.正常盛起将流体漏斗放置到世界中的液体装进ExU2铁桶
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10-64bit
 - 运行内存：6144M
 - Java版本：1.8.0_201
- 整合包版本*：1.2.8-beta

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2019-12-21_15.15.17-server.txt](https://github.com/ET-Team/EnigTech2/files/3991167/crash-2019-12-21_15.15.17-server.txt)

**Comment by JerryS116** [comment]
虽然是在操作ExU2桶时崩溃，但是同时由于炼油厂的输出，flopper的漏斗也在工作，崩溃是flopper导致的。目前还没有复现成功，之后如果复现了会再来报告。

**Comment by dong031001** [comment]
炼油厂输出可以由高级流体过滤器的预留流体功能来占位解决，且非整合包问题而是模组问题（特性），Issue2复现成功后请另开Issue
