### ISSUE TITLE
[BUG]无法使用骨粉催熟放在地上的神秘花花瓣

### ISSUE THREAD

**Issue by JerryS116** [ET-Team/EnigTech2#193]
**描述BUG**
将植物魔法的神秘花花瓣右击放在草方块上，再用骨粉右击，理应生成高神秘花，但是事实上无法实现
**如何重现**
将植物魔法的神秘花花瓣右击放在草方块上，再用骨粉右击
**原本期望**
产生高神秘花

**截图**
![图片](https://user-images.githubusercontent.com/43673838/71304977-82bd3e00-2408-11ea-8e87-1513c264f612.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10 64bit
 - 运行内存：6144M
 - Java版本：1.8.0_201
- 整合包版本*：1.2.9（1.2.8时初次发现此问题，但并不确定该版本是出现此问题的最早版本）

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
需要温室玻璃
