### ISSUE TITLE
[建议]关于整合包的一些建议

### ISSUE THREAD

**Issue by alkkhsl** [ET-Team/EnigTech2#196]
### 首先，感谢作者们为我们带来了这么精彩的整合包，整体体验非常好！从阶段的设定，模组的组合，配方的魔改，模块化机械的应用，在各个阶段，在不同程度上都给游戏带来的不同的乐趣！
>  总体感受：

P1-P5整体流程较为顺畅。P1流程稍显短暂，圣诞dlc非常不错，增加了一些难度和挑战。P2至P5流程体验均非常好。P6开始流程稍显拖沓，尤其进入P6后半段，自动化全面铺开后，受材料需求及机器速度的限制，会产生大量的挂机时间，这种挂机会卡住整体流程，产生过多的等待。Alpha阶段刚刚开始，我们看了整体看了大概流程、合成配方后，决定暂时结束，原因基于与P6后半程同样的问题，合成较复杂材料的过多等待挂机等。下面就我们在过程中一些粗糙的想法和建议，仅供参考，唐突之处请见谅。

>  一些具体的意见建议：

`1.余烬（Embers）`在没有TE管道加持下，较难实现自动化炼金等，所以余烬炼金加工的材料不适合在后期大量使用。比如黯淡盖亚水晶，消耗时长较大，在后期合成MEK、核电工艺等模组机械外壳上大量使用，让人抓狂。建议：加入TE管道便于实现炼金自动化，同时在P6阶段对余烬炼金材料添加更加简易的替代合成方式。

`2.模块化机械（Module Machinery）`
大型柴油锅炉与蒸汽涡轮定位较为尴尬，蒸汽涡轮因为前期无法提供足够蒸汽而无法发挥作用（P4阶段并没有大量使用余烬，单纯为烧蒸汽发电有些偏移模组本身的设定，其蒸汽仅供给蒸汽装配机使用则恰到好处）。而大型柴油锅炉需要钼钢块，需要在P5后期高级火箭上天后才能建造，而在此之前已经发展AE、EIO、TE、深度怪物学习、实用设备等众多耗电模组，此时蒸汽涡轮1024的发电也显得较为鸡肋了。 建议：P5阶段可增加更多蒸汽产出方式，大幅增加蒸汽涡轮发电量。

石油钻井平台用于供给润滑油、炼油气及火箭燃料来完成一些合成配方是较为合适的选择，但是其产出如果供给柴油锅炉，则对于铁（流体管道）的消耗有些入不敷出。建议：柴油锅炉可考虑添加多种燃料（固体、流体等）。

魔能高炉、魔力粉碎机、魔能磁化机等使用频率较高的机器在后期加工速度偏慢，大幅度拖慢了后期进程，产生非常多的无谓的等待。建议：增加机器可升级别，像魔能高炉可升级至MK5、增加魔能磁化机的更高级别版本等，同时提升相应级别的速度，用来满足后期科级线大量合成的需求。

魔能高炉作为贯穿后期主要加工机器，其使用的流体种类也较多，单一流体输入会影响体验，建议：灵活配置魔能高炉搭建方式，可选配多流体输入仓。

`3.沉浸工艺（Immersive Engineering）`
合金窑与强化高炉，在P6出核电工艺小制造机之前，硅的唯一产出方式为强化高炉；甚至解锁到alpha阶段强化硅的产出方式也仅仅只有用过合金窑（Ps：且合金窑无法连接管道实现自动化），硅作为工业科技发展的必备材料，显得产出过于单一。建议：在不同阶段增加硅的不同合成方式，由难至简，便于后期自动化合成。
粉碎机，作为沉浸核心机器之一，并没有在进度线上体现，其配方基本都可以通过roots模组的研钵来完成。建议：前期可删除焦煤粉等材料在研钵中的配方，仅限沉浸粉碎机合成。

`4.应用能源（Applied Energistics）`
存储元件，作为AE核心物品，其使用了过多的辉耀石英，而辉耀石英产出过于单一且缓慢（实际在我们服务器中4人共同产出，人均游戏时间逾100小时，除必要合成外，所产出的辉耀石英仅仅制作了50个16k存储元件）对于拥有环境科技这样海量产出模组的整合包来说，存储元件限制的稍显过度，且对单人玩家不够友好。建议：存储元件中减少辉耀石英的使用，或增加产出。

`5.等价交换（ProjectE）`
作为alpha阶段核心模组之一，在拥有能量凝聚器（BUG报告：能量凝聚器没有进行配方魔改，解锁alpha阶段即可获得，显得过于容易。）甚至转化桌后，因为大量合成物品及自定义物品没有价格，导致其并没有起到更大作用，无法产生质变的效果，没有达到模组本身的预期。建议：为中后期大量制作、流程繁琐及难以获得的材料制定合适价格，以拓展获取方式，。同时对出了转化桌后面的流程线、可考虑由堆材料转为实现更高阶的目标。（Ps：龙堆确实是个非常好的选择）

`6.创造物品`
创造转换套件用于TE保险箱时可将保险箱转为创造箱子，实现与创造抽屉取出升级同样的效果，在流程线上不应分列先后。同时建议：增加更多创造物品合成，同时可根据使用场景，适当提前部分创造物品阶段，来增强阶段性的成就感。（例如可考虑在P5阶段加入余烬创造能量、在P6阶段加入AE创造能源等）

**Comment by alkkhsl** [comment]
以上是一些我们经历专家模式后的一些体验，一点点个人观点仅供参考。（我们也许本身是比较肝的，这种玩法也许不适合大多数人，哈哈）

**Comment by dong031001** [comment]
感谢提供的宝贵建议，已经根据你的建议草拟出了具体的实现方案并将在1.2.10版本中更新

**Comment by dong031001** [comment]
肝完了
