### ISSUE TITLE
[崩溃]服务器生成地形时崩溃

### ISSUE THREAD

**Issue by Yunth233** [ET-Team/EnigTech2#232]
服务器生成地形时崩溃

**错误报告** 
[crash-2019-12-28_19.28.55-server.txt](https://github.com/ET-Team/EnigTech2/files/4006982/crash-2019-12-28_19.28.55-server.txt)

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：6g
 - Java版本：jdk-8.0.212.04-openj9
- 整合包版本*：1.2.10

**Comment by dong031001** [comment]
原因为Sponge端对Triumph自定义成就函数的不兼容，请更换服务器核心

**Comment by dong031001** [comment]
你也可试试删除FTBU模组，因插件可以替代FTBU模组的所有功能

**Comment by Yunth233** [comment]
好的，谢谢
