### ISSUE TITLE
[BUG]放下数字化苦难之井后崩溃，vanillafix显示崩溃来源则为Embers Rekindled

### ISSUE THREAD

**Issue by Control-Core** [ET-Team/EnigTech2#235]
**描述BUG**
放下数字化苦难之井后崩溃，vanillafix显示崩溃来源则为Embers Rekindled
**如何重现**
放下数字化苦难之井
**原本期望**
若无此BUG，原本你期待发生什么？
正常运行，无崩溃
**截图**
![snipaste20191230_155056](https://user-images.githubusercontent.com/20108500/71572896-31096780-2b1c-11ea-89d4-69da7db31f34.png)

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2019-12-30_15.40.30-client.txt](https://github.com/ET-Team/EnigTech2/files/4009199/crash-2019-12-30_15.40.30-client.txt)

**Comment by dong031001** [comment]
无法重现
