### ISSUE TITLE
[崩溃]火箭落地时，服务器直接崩溃

### ISSUE THREAD

**Issue by Yunth233** [ET-Team/EnigTech2#237]
报告:
[crash-2019-12-30_21.25.47-server.txt](https://github.com/ET-Team/EnigTech2/files/4010000/crash-2019-12-30_21.25.47-server.txt)
[crash-2019-12-30_20.55.01-server.txt](https://github.com/ET-Team/EnigTech2/files/4010001/crash-2019-12-30_20.55.01-server.txt)

**Comment by dong031001** [comment]
非官服问题请一概发布到对应核心页面

**Comment by Yunth233** [comment]
好的
