### ISSUE TITLE
[BUG]服务端掉线问题

### ISSUE THREAD

**Issue by chenwenjie27** [ET-Team/EnigTech2#258]
**描述BUG**
用服务端进游戏, 玩个十几二十几分钟就会掉线, 客户端提示说什么致命错误, 然后需要
重新进服务器, 而且第一次重进还是会掉线, 要重进两次才可以.
**如何重现**
在服务端进行游戏, 挂机个十几二十几分钟即会掉线
**原本期望**
和小伙伴愉快的挂机刷资源, 而不会觉得挂机没用, 走开后一会还是会掉线啥的...
**截图**
![image](https://user-images.githubusercontent.com/44220311/71779858-88fd0e00-2ff5-11ea-8155-19c8d4d393cc.png)
 - 客户端掉线显示
**运行环境（请越详细越好）:**
 - 操作系统*： Windows 10 企业版
 - 运行内存： 16G
 - Java版本：jre1.8.0_191
- 整合包版本*：EnigTech2 1.2.10

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
服务端控制台并无错误信息, 客户端的crash-report也无错误报告

**Comment by dong031001** [comment]
如果可以，请附上游戏根目录的log文件夹内标注问题发生日期的文件

**Comment by chenwenjie27** [comment]
[latest.log](https://github.com/ET-Team/EnigTech2/files/4023406/latest.log)
这个21:03分正是我掉线的时刻, 请看错误信息

**Comment by chenwenjie27** [comment]
如果可以通过修改配置什么的来解决的话, 请告诉我下改哪里, 如果要做比较大的Mod调整的话, 我还是等下次更新

**Comment by dong031001** [comment]
[21:03:35] [Netty Client IO #5/ERROR] [FML]: EntitySpawnHandler exception
io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (1958335 > 1024)
这是报错原因 粗略判断是由于服务端发包超限导致的，可以由server.properties文件中更改限制

**Comment by chenwenjie27** [comment]
需要修改哪一项, 修改值需要为多少, 能不能设为不限制

**Comment by dong031001** [comment]
network-compression-threshold
将这个条目（可能需自行创建）设置为1024以下即可

**Comment by dong031001** [comment]
或者直接设置为-1 取消限制

**Comment by chenwenjie27** [comment]
这个我的配置文件内本身就设置为256, 是1024以下呀

**Comment by chenwenjie27** [comment]
我试试

**Comment by chenwenjie27** [comment]
还是会掉线哦, 但是这次掉线服务端有报错信息:
[11:35:46] [Netty Server IO #5/ERROR] [FML]: NetworkDispatcher exception
[latest.log](https://github.com/ET-Team/EnigTech2/files/4024643/latest.log)
这个是客户端报错内容

**Comment by dong031001** [comment]
考虑java版本问题或服务端过载
