### ISSUE TITLE
你们搞的这个ET License真的没有问题??

### ISSUE THREAD

**Issue by Chenwe-i-lin** [ET-Team/EnigTech2#275]
作为制作组, 你们的辛劳值得肯定, 但是这个ET License上来就说"我爱咋咋地", 总感觉有点冒犯  
并且制作组将 `mods` 文件夹**直接**放到github上来, 真的没问题吗? **Github不是网盘, git也不是OSS-cli**, 并且敢问贵组有没有考虑到各个模组的使用授权与所谓ET License的冲突?

**Comment by dong031001** [comment]
你可以制作出一个禁止Redistribution/禁止整合包使用的模组列表出来，我来考虑使用manifest替代

**Comment by Chenwe-i-lin** [comment]
我还是推荐使用 `manifest` 这种方式分发mod.  

emmm, 我刚才看到了贵repo被某个主播修改/买卖, 在此表示愤慨..., 但是大部分mod应该都是拒绝二次分发的(可能需要证实), 并且你整的这一出`保留一切权利`我觉得是保留了整合包的处置权和创作权等, 也许并不包括整合包中一些Mod的二次分发权...  
另外, 建议使用CC协议, CC协议并不是用了版权就归CC了, 具体请百度  
希望贵组权衡利弊, 改进这些问题....

**Comment by dong031001** [comment]
已经修改LICENSE内容

**Comment by Chenwe-i-lin** [comment]
感谢回复.

**Comment by dong031001** [comment]
> 感谢回复.

顺便一提，无论是CC，MIT，GPL，都是在条款里声明可以不做任何修改的分发的。一般的前提为为原作署名，而mod.INFO中都有写明作者的ID的。并且，在原作发布页面下方Declare了任何类似“Feel free to use in any modpacks”都视作已经给过授权了。除非ALL RIGHTS RESERVED的模组需要EXPLICIT授权，且ARR的模组也都违反了FORGE的协议和EULA，所以应当视作无效。

**Comment by Chenwe-i-lin** [comment]
~~我想了下, 但是好像再想下去就要扯到法律了, 很麻烦~~
那么什么时候能用上manifest呢?

**Comment by dong031001** [comment]
> ~我想了下, 但是好像再想下去就要扯到法律了, 很麻烦~
> 那么什么时候能用上manifest呢?

其实已经用上了的...详见ET2的CF页面，只是为了国内玩家下载方便，不必等几个小时下载模组才分发了带有模组源文件的版本，且这个仓库是直接从运行环境中使用GITIGNORE部分截取下来的，主要是为了方便协作且能够记录模组变动。

**Comment by Chenwe-i-lin** [comment]
是这样吗, 我可能以后会写一个脚手架来帮助整合包作者使用git进行协同创作...

**Comment by dong031001** [comment]
> 是这样吗, 我可能以后会写一个脚手架来帮助整合包作者使用git进行协同创作...

已删除所有模组备份改用manifest.json
