### ISSUE TITLE
玄理矿物百科在服务端无法打开

### ISSUE THREAD

**Issue by Hangree134** [ET-Team/EnigTech2#290]
**描述BUG**
server端patchouli_books文件夹内为空导致服务器内无法打开玄理矿物百科

**如何重现**
server端开服，获取 玄理矿物百科 右键

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
复制客户端文件夹至服务端根目录即可解决，下一版本服务端会修复的。
