### ISSUE TITLE
[BUG]沉浸科技

### ISSUE THREAD

**Issue by ChristorRIRO** [ET-Team/EnigTech2#292]
**描述BUG**
无法查询沉浸科技^金属冲压模具:板材等
**如何重现**

**原本期望
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win64
 - 运行内存：4096
 - Java版本：jdk1.8.0_131
- 整合包版本*：enitech2-v1.3.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件^未崩溃

**Comment by ChromaPIE** [comment]
请阁下详细描述自己所处的游戏阶段并最好附上截图

**Comment by ChromaPIE** [comment]
无法复现
