### ISSUE TITLE
[BUG]连锁砍树

### ISSUE THREAD

**Issue by damonlee1234** [ET-Team/EnigTech2#293]
**描述BUG**
当连锁砍树2以上，一次性砍非常多的树，会把斧头砍爆(1000耐久也会爆)

**如何重现**
把所有树苗插满9x9
**原本期望**
一次性砍多个树

**截图**
![Uploading 2020-01-28_03.51.03.png…]()

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：6gb
 - Java版本：8.0.2410.7
- 整合包版本*：enigtech2 1.3.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
此为附魔特性。请尝试再做一把耐久更高的斧子。

**Comment by damonlee1234** [comment]
谢谢
