### ISSUE TITLE
[BUG]进度中关于符文的文字错误

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#294]
**描述BUG**
第二阶段进度中关于符文的进度的描述里面“制作”重复了两次
**如何重现**
查看第二阶段的关于符文的进度
**原本期望**
若无此BUG，原本你期待发生什么？
只有一个“制作”
**截图**
![Annotation 2020-01-28 133327](https://user-images.githubusercontent.com/11871061/73238125-c73fb480-41d2-11ea-98b4-136564061fe6.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.2.12

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
@tuna5544
