### ISSUE TITLE
[BUG] 1.3版本铱锇合金配方无法于魔能高炉MK2组装前制作

### ISSUE THREAD

**Issue by Tine1441** [ET-Team/EnigTech2#295]
整合包版本1.3，1.2.12版本存在的使用铱粉与锇粉制作铱锇合金的配方遭到了移除，这导致了阶段五早期的玩家无法制作超导电机进而进行下一步的发展。需要尽快修复

**Comment by ChromaPIE** [comment]
**已受理**。

**此次改动原因为**：原本的粉-粉-奥源-龙息合成配方在原料配给不到位的情况下会导致上述两种粉因为已满足高炉的激活条件而被处理为锭。不利于精准配给系统缺失时的合成操作，故改为锭-锭-奥源-龙息合成。未考虑到锇必须使用MK2烧制，致歉在此。

@tuna5544 @dong031001 给锇一个MK1配方会有问题吗？

**Comment by NonToxicEel** [comment]
无问题，但锇锭为阶六物品，需要额外移出阶段才可使用。

**Comment by ChromaPIE** [comment]
劳驾。或告知在何处移出

**Comment by dong031001** [comment]
> 劳驾。或告知在何处移出

已经**移出**
