### ISSUE TITLE
[BUG]辉耀工作台吞物品

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#298]
点击辉耀工作台右边格子里保存的配方消耗了原料却未得到产物
**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10家庭中文版
 - 运行内存：8.00GB
 - Java版本：JAVA8
- 整合包版本*：1.3.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
请附上视频文件/截图文件以及欲合成物品

**Comment by CsyBarry** [comment]
![EnigTech2-v1 3 0 2020-01-29 13-06-12 00_00_05--00_00_16](https://user-images.githubusercontent.com/60415944/73329690-8ced1a80-4299-11ea-945c-008b2c6e6459.gif)
![EnigTech2-v1 3 0 2020-01-29 13-06-12 00_00_52--00_01_05](https://user-images.githubusercontent.com/60415944/73329695-9080a180-4299-11ea-9db9-916f06dd2a9e.gif)

从测试结果来看似乎有多个物品有这种情况

**Comment by dong031001** [comment]
辨明问题为package阶段，将在下个版本修复。
