### ISSUE TITLE
[BUG]骨粉不可用

### ISSUE THREAD

**Issue by gitigitiaayyyeeee** [ET-Team/EnigTech2#299]
**描述BUG**
骨粉对任何作物、植物无效，右键无反应。
**如何重现**
不知道。。。
**原本期望**
若无此BUG，原本你期待发生什么？
用骨粉催化作物
**截图**
nope（都说了没反应了！你在期待什么？手里拿着骨粉的截图么？！）
**运行环境（请越详细越好）:**
 - 操作系统*：WIN10
 - 运行内存：16G(分配了4096mb)
 - Java版本：64位 1.8.0_241
- 整合包版本*：engitech2 1.2.9

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
没崩

**Comment by gitigitiaayyyeeee** [comment]
极其讨厌，骨粉不能用后我装了加速火把，结果加速火把还被作者禁用了。。。

**Comment by gitigitiaayyyeeee** [comment]
求赶紧修bug,或者把加速火把禁用去了，游戏体验极差

**Comment by CsyBarry** [comment]
作物和树苗有对应的生长季节，生长季节不对是无法用骨粉催熟，建议制作温室玻璃来解决你的问题

**Comment by CsyBarry** [comment]
不要随意使用加速火把，拆解台和连锁挖矿来破坏前期游戏平衡

**Comment by gitigitiaayyyeeee** [comment]
> 不要随意使用加速火把，拆解台和连锁挖矿来破坏前期游戏平衡

可是因为生活原因我没有多少时间等待，实在没时间等，尤其是第二阶段的大炉子，极慢。

**Comment by CsyBarry** [comment]
> 不要随意使用加速火把，拆解台和连锁挖矿来破坏前期游戏平衡
> 
> 可是因为生活原因我没有多少时间等待，实在没时间等，尤其是第二阶段的大炉子，极慢。

那可能比较麻烦了，设备的更新和强化都在中后期的阶段，但总体上来说发展是一个加速的趋势

**Comment by ChromaPIE** [comment]
原则上禁止任何向本包加入作弊模组的行为。如果本包对您的生活造成了影响，请放弃本整合包。此外，阁下在由于自己模组知识匮乏而导致误判所谓“BUG”的情况下仍大放厥词并拿出自己加装作弊模组的事例前来报喜，其作风作为令人叹为观止。
