### ISSUE TITLE
[BUG]改动未生效

### ISSUE THREAD

**Issue by Huaxidesu233** [ET-Team/EnigTech2#300]
https://sm.ms/image/ZuOV4ovh75JzXpI
https://sm.ms/image/vaRYP8OQFo4JhZ
上图改动未生效，东西还可以做，就是要用原本的配方，但是，JEI里已经是显示的这个合成表了

**Comment by ChromaPIE** [comment]
无法重现。改动已生效。请阁下检查整合包更新是否完整
