### ISSUE TITLE
[BUG]在焦炉里烧制煤炭块会出现热力膨胀的焦炭块而不是沉浸工程的焦煤块

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#301]
**描述BUG**
RT，虽然焦炭和焦煤可以混用，但还是希望统一一下，**最好能加入合成配方把现有的焦炭和焦炭块转换成焦煤和焦煤块**
**如何重现**
在焦炉里烧制*煤炭块*
**原本期望**
若无此BUG，原本你期待发生什么？
在焦炉里烧制煤炭块后出现焦煤块而不是焦炭块。
**截图**
![批注 2020-01-30 134718](https://user-images.githubusercontent.com/11871061/73423586-86c56f80-4367-11ea-988b-62d023e85409.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.2.12

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by sjdhome** [comment]
似乎在焦炉里的时候和刚拿出来的时候是正常的，拿出来之后关闭背包界面再打开之前的焦煤块就变成焦炭块了。

**Comment by ChromaPIE** [comment]
:-)

**Comment by sjdhome** [comment]
？

**Comment by ChromaPIE** [comment]
**不予修复/改动。**

矿辞统一已经达到了应有的效果。

**Comment by sjdhome** [comment]
> **不予修复/改动。**
> 
> 矿辞统一已经达到了应有的效果。

好吧，我提这个的原因之一是因为你们在焦煤上做了一个不是优质燃料的提示而焦炭上没有。
