### ISSUE TITLE
[BUG]耐火混合物无法合成

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#303]
无法按照合成表中的配方成功制作耐火混合物
**运行环境（请越详细越好）:
 - 操作系统*：Windows10
 - 运行内存：8.00GB
 - Java版本：Java8
- 整合包版本*：1.3.0 专家模式

![Awww man](https://user-images.githubusercontent.com/60415944/73537592-cffae980-4463-11ea-81a6-054dbcefce31.gif)

**Comment by ChromaPIE** [comment]
开发版已修复
