### ISSUE TITLE
[BUG]刷物品

### ISSUE THREAD

**Issue by Huaxidesu233** [ET-Team/EnigTech2#307]
如图，在老版本和1.3.0版本都有
https://upload.cc/i1/2020/02/01/bS6mhJ.jpg
https://upload.cc/i1/2020/02/01/9Sgp5K.jpg
https://upload.cc/i1/2020/02/01/0NRvJz.jpg
https://upload.cc/i1/2020/02/01/cq3X8P.jpg
https://upload.cc/i1/2020/02/01/Qnz91s.jpg

**Comment by ChromaPIE** [comment]
请联系相应模组作者。此外，图中物品多刷无明显意义。
