### ISSUE TITLE
[其他]优化扫描器的结果显示和其他

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#309]
建议增强扫描器扫描矿石结果的辨识度，即用区分度更高的颜色区分不同矿石，另外扫描器扫描后会将后面阶段的当前仍显示为石头的矿物方块标记上颜色，建议优化

**Comment by ChromaPIE** [comment]
提交建议前请**思考**您即将反馈的问题**是否属于整合包范畴**。

上述反馈的解决请直接联系Scannable作者以建议其进行关于可读性及GameStage兼容的更改：

Scannable的CurseForge页面：https://minecraft.curseforge.com/projects/scannable?gameCategorySlug=mc-mods&projectID=266784
Scannale的GitHub仓库：https://github.com/MightyPirates/Scannable
