### ISSUE TITLE
[BUG] 脉络与连锁砍树附魔书问题深修

### ISSUE THREAD

**Issue by ChromaPIE** [ET-Team/EnigTech2#311]
附魔书的NBT引用的都是附魔的数字ID，而这个数字ID会莫名其妙发生变更（ @dong031001 ） 导致配方错误地合成了另一本附魔书。如1.3.0中，测试时无问题（非release前最终测试），后不知因何改动导致两者分别指向了幽影步与加热附魔；而1.3.1版本中，两者又指向了洞察与魔力浓稠附魔。推测为数字ID的问题。

而寂静宝石提供的附魔徽章NBT则直接引用了附魔的文字ID，如“veining”即脉络。又想到久前在私包练手脚本编写时，曾为附魔徽章添加过配方，无任何问题发生。

最后，建议将两个附魔直接重新设计为合成附魔徽章（ @ChromaPIE  ），并重构相关进度（ @tuna5544  ）。

**Comment by friendlyhj** [comment]
~~用数字ID的都是屑了~~

我可以帮忙修下关于ZenScript的问题，要尽量避免使用数字ID

**Comment by friendlyhj** [comment]
刚刚下了新的1.3.1的包，并没有此问题...
