### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#313]
复制存档到新版本之后出现进度内容丢失，在该存档中试图切换创造模式会导致游戏崩溃
![批注 2020-02-03 133217](https://user-images.githubusercontent.com/60415944/73627951-a91dfc80-4689-11ea-9ac9-6e1f53312dc6.png)
注：印象中此前从未出现过图中模组崩溃的情况
如果这种情况与启动器有关，请详细说明，十分感谢
旧版本启动器为hcml，新版本为MultiMC
已在其他此版本的存档中进行测试，可以切换创造模式，可以通过命令与物品解锁阶段物品，但不能解锁阶段进度，即我无论在什么阶段都只有阶段一和根源的进度

![](file:///E:/MultiMC/instances/EnigTech2/minecraft/screenshots/2020-02-03_13.41.06.png)

![](file:///E:/MultiMC/instances/EnigTech2/minecraft/screenshots/2020-02-03_13.41.15.png)

![](file:///E:/MultiMC/instances/EnigTech2/minecraft/screenshots/2020-02-03_13.41.23.png)

![](file:///E:/MultiMC/instances/EnigTech2/minecraft/screenshots/2020-02-03_13.41.34.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10
 - 运行内存：8.00GB
 - Java版本：Java8
- 整合包版本*：1.3.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-02-03_13.25.58-server.txt](https://github.com/ET-Team/EnigTech2/files/4146407/crash-2020-02-03_13.25.58-server.txt)

**Comment by CsyBarry** [comment]
最新测试结果：
我可以在hmcl正常游玩1.3.0
MultiMC下1.3.0版本仍有上述问题（似乎的确是启动器的问题）
我无法于hmcl下游玩1.3.1，提示“安装失败” XD



![2020-02-03_13 41 06](https://user-images.githubusercontent.com/60415944/73637997-7fbe9a00-46a4-11ea-8442-841ff5f5bbd2.png)
![2020-02-03_13 41 15](https://user-images.githubusercontent.com/60415944/73637999-80efc700-46a4-11ea-9fac-a8c10c7b3b56.png)
![2020-02-03_13 41 23](https://user-images.githubusercontent.com/60415944/73638000-81885d80-46a4-11ea-9437-05f1a812c48e.png)
![2020-02-03_13 41 34](https://user-images.githubusercontent.com/60415944/73638002-8220f400-46a4-11ea-8223-2e8c087e9bb0.png)

**Comment by dong031001** [comment]
是否有正盗版切换的行为？

**Comment by CsyBarry** [comment]
> 是否有正盗版切换的行为？

有

**Comment by dong031001** [comment]
> > 是否有正盗版切换的行为？
> 
> 有

尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题

**Comment by CsyBarry** [comment]
> 是否有正盗版切换的行为？
> 
> 有
> 
> 尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题

这应该就是原因所在了，刚刚发现在hmcl下用正版登录后原本可以正常离线游玩的存档同样出现上述问题，感谢你们提供的帮助。

**Comment by CsyBarry** [comment]
> 是否有正盗版切换的行为？
> 
> 有
> 
> 尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题
……恕我才疏学浅，只能用universal minecraft editor查看正盗版的UUID，却不知如何修改

**Comment by dong031001** [comment]
> > 是否有正盗版切换的行为？
> > 有
> > 尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题
> > ……恕我才疏学浅，只能用universal minecraft editor查看正盗版的UUID，却不知如何修改

在你出问题的存档内的playerdata文件夹内有以UUID命名的文件夹，重命名覆盖即可，注意子文件夹内的文件也需照此般。

**Comment by CsyBarry** [comment]
> 是否有正盗版切换的行为？
> 有
> 尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题
> ……恕我才疏学浅，只能用universal minecraft editor查看正盗版的UUID，却不知如何修改
> 
> 
> 在你出问题的存档内的playerdata文件夹内有以UUID命名的文件夹，重命名覆盖即可，注意子文件夹内的文件也需照此般。

问号的问题解决了，接下来是进度信息的问题，已经知道只有按照流程重新走一遍才能解锁阶段，无法直接通过命令与最终物品解锁，在那个存档中尝试打开“对局域网开放”会导致图一中两个模组崩溃

**Comment by dong031001** [comment]
> > 是否有正盗版切换的行为？
> > 有
> > 尝试在存档内将盗版UUID的玩家数据重命名为你的正版UUID，应该可以解决你的问题
> > ……恕我才疏学浅，只能用universal minecraft editor查看正盗版的UUID，却不知如何修改
> > 在你出问题的存档内的playerdata文件夹内有以UUID命名的文件夹，重命名覆盖即可，注意子文件夹内的文件也需照此般。
> 
> 问号的问题解决了，接下来是进度信息的问题，已经知道只有按照流程重新走一遍才能解锁阶段，无法直接通过命令与最终物品解锁，在那个存档中尝试打开“对局域网开放”会导致图一中两个模组崩溃

/advancement grant until et2:stageTwo/root 可以解锁阶段二的根进度，你可以照搬与其他阶段

**Comment by CsyBarry** [comment]
一旦我选择“对局域网开放——允许创造：开——创建一个局域网世界”，图一的两个模组就会崩溃，然后回到标题界面，之后重进游戏又需要重新试图开启允许作弊，如此循环，我似乎永远无法达到成功使用命令的【真实】

**Comment by dong031001** [comment]
> 一旦我选择“对局域网开放——允许创造：开——创建一个局域网世界”，图一的两个模组就会崩溃，然后回到标题界面，之后重进游戏又需要重新试图开启允许作弊，如此循环，我似乎永远无法达到成功使用命令的【真实】

NBTExplorer可以修改存档是否可以作弊

**Comment by CsyBarry** [comment]
也许我可以直接修改这些东西，直到我的存档恢复原样：）
![屏幕截图(3)](https://user-images.githubusercontent.com/60415944/73673740-2711f000-46ea-11ea-8772-efaf77f351a6.png)
