### ISSUE TITLE
[BUG]JEI显示很多空部件

### ISSUE THREAD

**Issue by friendlyhj** [ET-Team/EnigTech2#315]
**描述BUG**
如图
**如何重现**
解锁第五阶段后，JEI搜索`@contenttweaker` 
**原本期望**
JEI不显示空部件

**截图**
![](https://upload.cc/i1/2020/02/03/5RzA6k.jpg)
![](https://upload.cc/i1/2020/02/03/jhP6Nk.jpg)

**运行环境（请越详细越好）:**
 - 操作系统*：Win10
 - 运行内存：4G
 - Java版本：Java8 241
- 整合包版本*：1.3.1

**错误报告** 
Nothing
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
移除EMC无法解决空部件问题。所有移除的EMC值已在即将推送的PR中恢复。

**Comment by friendlyhj** [comment]
https://github.com/ET-Team/EnigTech2/blob/fb9d2f7323b8f7a954e334093e3e8ab4e6d8b4b6/EnigTech2/minecraft/scripts/crafttweaker/normal/staging/Items.zs#L325-L327

应该是这里出的问题

**Comment by dong031001** [comment]
> https://github.com/ET-Team/EnigTech2/blob/fb9d2f7323b8f7a954e334093e3e8ab4e6d8b4b6/EnigTech2/minecraft/scripts/crafttweaker/normal/staging/Items.zs#L325-L327
> 
> 应该是这里出的问题

确实如此，感谢提醒。
