### ISSUE TITLE
[BUG]部分矿物及其衍生物名称显示不全

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#321]
如题，并未导致除一脸懵逼以外的其他问题

**截图**
![2020-02-04_20 32 46](https://user-images.githubusercontent.com/60415944/73745468-0e5b1600-478e-11ea-8179-503fca5f5e56.png)
![2020-02-04_20 32 59](https://user-images.githubusercontent.com/60415944/73745471-1024d980-478e-11ea-9e28-d233ba9a6196.png)
![2020-02-04_20 33 02](https://user-images.githubusercontent.com/60415944/73745472-11560680-478e-11ea-9a60-1986c1eef8f9.png)
![2020-02-04_20 33 15](https://user-images.githubusercontent.com/60415944/73745477-12873380-478e-11ea-8926-c4d4b2ec3120.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10
 - 运行内存：8.00
 - Java版本：Java8
- 整合包版本*：1.3.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
#310
