### ISSUE TITLE
[BUG]cuisine木手柄需要满耐久符文剪刀

### ISSUE THREAD

**Issue by Control-Core** [ET-Team/EnigTech2#323]
**描述BUG**
符文剪刀耐久不满时无法制作cuisine木手柄
**如何重现**
使用符文剪刀后进行cuisine木手柄制作
**原本期望**
若无此BUG，原本你期待发生什么？
可以成功之作
**截图**

![snipaste20200205_050818](https://user-images.githubusercontent.com/20108500/73787109-8f89cb80-47d5-11ea-813a-02e23763b74f.png)

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by Control-Core** [comment]
![snipaste20200205_050649](http://user-images.githubusercontent.com/20108500/73787760-e0e68a80-47d6-11ea-856d-c7b166fbb172.png)

**Comment by Control-Core** [comment]
![snipaste20200205_050649](https://user-images.githubusercontent.com/20108500/73787837-01aee000-47d7-11ea-9c24-f44b5301f6bd.png)

**Comment by ChromaPIE** [comment]
设计如此。
