### ISSUE TITLE
[BUG]高炉燃料说明显示错误

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#325]
**描述BUG**
RT，出现Format error
**如何重现**
打开高炉界面，点击箭头，然后进入燃料选项卡
**原本期望**
若无此BUG，原本你期待发生什么？
正常显示
**截图**
![批注 2020-02-05 161130](https://user-images.githubusercontent.com/11871061/73823020-5af82d00-4832-11ea-8b4f-0635e38b1404.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.3.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
IE 语言key问题
