### ISSUE TITLE
[BUG]自然灵气之书遇到问题

### ISSUE THREAD

**Issue by lbx000203** [ET-Team/EnigTech2#326]
**描述BUG**
打开自然灵气之书后提示加载时遇到错误

**如何重现**
进入存档后打开自然灵气之书，进入任意目录，关掉书，再打开，触发游戏崩溃
VanillaFix提示Patchouli遇到问题

**原本期望**
若无此BUG，原本你期待发生什么？
正常使用自然灵气之书

**截图**
![批注 2020-02-05 185008](https://user-images.githubusercontent.com/38578998/73836937-5a1fc500-484b-11ea-863c-123d8060b73f.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：8.0G
 - Java版本：AdoptOpenJDK/jdk-8.0.202.08
- 整合包版本*：1.3.1
- 启动器：multimc

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-02-05_18.06.46-client.txt](https://github.com/ET-Team/EnigTech2/files/4159128/crash-2020-02-05_18.06.46-client.txt)

**Comment by lbx000203** [comment]
发现bug时使用的multimc版本是develop最新版，切换回stable 0.6.7-1375 版本后无此bug

**Comment by dong031001** [comment]
初步判断原因为MultiMC开发版本缺失某些必要的GSON依赖库，请移步 https://github.com/MultiMC/MultiMC5/issues
