### ISSUE TITLE
[其他]希望可以添加植物魔法魔力符文的压印器配方

### ISSUE THREAD

**Issue by Control-Core** [ET-Team/EnigTech2#329]
其他所有符文都有压印器替代配方只有魔力符文没有

**Comment by ChromaPIE** [comment]
阁下是需要**大批量**制作：

- 泰拉凝聚板
- 魔力脉冲枪
- 植物酿造台
- 光环之戒
- 高级工作台
- 神社庭灯
- 阿卡纳蔷薇
- 魔力池（普通）
- 精灵门核心

中的一种或多种吗？
