### ISSUE TITLE
[BUG]偶现的能源输入仓无法输入问题

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#331]
在一次供电事故（指未及时打开发电机供电）后，能源输入仓无法正常输入电力，机器也无法正常工作，需要拆下能源输入仓重新放置才能正常充满电一次，不过哪怕是这样依旧会在内部存储消耗完以后变成上文所述的模样，因为要拆卸能源输入仓，如果机器此前正在工作，则会吞掉正在处理的原料
以下是故障的能源输入仓

![awww man](https://user-images.githubusercontent.com/60415944/74043877-1c669c00-4a05-11ea-9404-29f167eaef7c.gif)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10
 - 运行内存：8.00
 - Java版本：Java8
- 整合包版本*：1.3.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
尝试过独立供电吗？

**Comment by ChromaPIE** [comment]
阁下似乎非常乐意将ET-Team视作**其名下所有整合包中所包含的所有模组的作者**。我将以在您在本仓库反馈**Scannable相关问题**的issue回复格式**照搬**过来回复您的此篇issue，以下是正文：

---

提交建议前请**思考**您即将反馈的问题**是否属于整合包范畴**。

上述反馈的解决请直接联系Modular Machinery作者以建议其进行关于能源输入仓的优化工作。

Scannable的CurseForge页面：https://www.curseforge.com/minecraft/mc-mods/modular-machinery
Scannable的GitHub仓库：https://github.com/HellFirePvP/ModularMachinery/
