### ISSUE TITLE
[BUG]服务端流量异常

### ISSUE THREAD

**Issue by Kelcoin** [ET-Team/EnigTech2#332]
**描述BUG**
服务端流量占用异常，单个玩家占用流量将近5Mb/S
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![I@Q4`LWRM($B4 ET Z3Z`LM](https://user-images.githubusercontent.com/10922375/74059740-90b03800-4a23-11ea-9510-67cd75a1da3a.png)

**运行环境（请越详细越好）:**
 - 操作系统*：debian 9.6
 - 运行内存：8G
 - Java版本：openjdk8
- 整合包版本*：1.3.1r

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
如非生产环境，可否附上服务端日志文件与流量监控图表（正负5分钟）？

**Comment by Kelcoin** [comment]
![FP0{0SYZ_V@ CHPR15FLG J](https://user-images.githubusercontent.com/10922375/74062008-48dfdf80-4a28-11ea-9d44-788dd798af19.png)
![E1(19MB%8JCN(ZYBMEPET{P](https://user-images.githubusercontent.com/10922375/74062012-4aa9a300-4a28-11ea-9f1a-81c115d13c8c.png)
几处凹陷为关闭服务器寻找问题时
[logs.zip](https://github.com/ET-Team/EnigTech2/files/4172752/logs.zip)

**Comment by Kelcoin** [comment]
![M8)34CRXS}6HH9K`1CF NIG](https://user-images.githubusercontent.com/10922375/74062238-c99edb80-4a28-11ea-84af-da6f07bc8045.png)

![7X980W`95I%NGU}2P~5 482](https://user-images.githubusercontent.com/10922375/74062374-14205800-4a29-11ea-9832-2de39e431847.png)

入站出站出了ssh等服务，就开了25565，后台也可以看到是java在占用带宽，可以确定是MC服务端的问题，就是无法查出真实原因，怀疑是某个mod在反复交互数据，占用满一段时间后会恢复正常然后又上升反复

**Comment by Kelcoin** [comment]
[latest.log](https://github.com/ET-Team/EnigTech2/files/4172860/latest.log)
服务端日志

**Comment by dong031001** [comment]
日志中无有效信息，应为特定模组问题，下版本会尝试更新所有模组版本，感谢反馈
