### ISSUE TITLE
[BUG]女仆的交互面板和InstandUnify冲突

### ISSUE THREAD

**Issue by AnTengye** [ET-Team/EnigTech2#333]
**描述BUG**
女仆的交互面板和InstandUnify冲突
**如何重现**
我测试了仅装了InstandUnify和TouhouLittleMaid时
给箱子添加交互面板，并设置对应白名单物品，模式为输入，女仆物品栏中加入对应物品。
此时，女仆对面板并没有任何反应。
**原本期望**
若无此BUG，原本你期待发生什么？
女仆能够将物品放入箱子中
- 整合包版本*：
1.3.1

**Comment by AnTengye** [comment]
@dong031001 EnigTech2的1.3.1的版本加入了女仆模组，我在创造模式测试时发现存在交互面板无法使用的情况，最后排查出是InstandUnify的问题，望解决，对于女仆模组还是十分欢迎的。

**Comment by ChromaPIE** [comment]
> @dong031001 EnigTech2的1.3.1的版本加入了女仆模组，我在创造模式测试时发现存在交互面板无法使用的情况，最后排查出是InstandUnify的问题，望解决，对于女仆模组还是十分欢迎的。

整合包已经为InstantUnify做了适配。不予受理，在此致歉。若阁下偏好UniDict并希望享受女仆交互面板的功能，可自行更换并解决可能出现的问题，绝对无可厚非。两者的兼容问题已有issue，修复可期。
