### ISSUE TITLE
神龙反应堆输出倍率800000真的能用吗

### ISSUE THREAD

**Issue by Guanxinyi-cookies** [ET-Team/EnigTech2#350]
由于最后要做固态能量，发现现有的算得上大点的发电设施，两个聚变反应堆和环境科技的六级太阳能实在带不动，离8万亿FE遥遥无期，于是想尝试下神龙反应堆。既然推荐，想来是有修改产出。
于是开了个超平坦进行测试，
当充能完 控制场50%，能量存储50%，热量2500点击激活就瞬间爆炸，尝试将能量注入器下能量阀门设为上限就是那个21亿多（大概吧），下面用的龙研模组里自带的创造RF能源，然后在一端稳定器后接凛冰能量管道接到能量塔上，点击激活也还是直接爆炸。然后也试了能量注入器下方不用阀门直接连接RF能源，结果一样。
看了下cfg发现有个reactoroutputmultiplier 是800000
不知道是BUG还是因为倍率太高而压不住。
游戏版本是1.3.3 运行环境:win10 LSTC 2019
java版本 jdk 8u211 
建议：适当下调倍率？或寻找能替代的高效发电 毕竟mek的核聚变ban了
如果只是因为我不会玩，建议适当给出些提示。

最后非常感谢作者和作者的团队带来这么精彩的整合包，真的很棒（就是有点肝）

**Comment by dong031001** [comment]
参考http://129.211.167.41/index.php/%E6%95%99%E7%A8%8B/%E5%85%B3%E4%BA%8EET2%E9%BE%99%E5%A0%86

**Comment by Guanxinyi-cookies** [comment]
非常感谢，教程很详细，辛苦啦

**Comment by dong031001** [comment]
> 非常感谢，教程很详细，辛苦啦

教程系 @Death-123 所作，私仅提供平台。
