### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by starsforest** [ET-Team/EnigTech2#353]
**描述BUG**
进度到达普通模式alpha阶段，通过查看配方后续是需要用到大量共振宝石的，但发现星能聚合器不能通过使用者塞入海蓝宝石（实际上聚星缸也无法塞入），求本身也不能通过物品管道传输物品，这就导致无法自动化共振宝石。如果有其他自动获得共振宝石的方法，麻烦给点提示。
另外，阶段六里使用了更替之星的聚变堆核心和守序者徽章，阶段alpah里使用了贤者宝石的灵素精华都要用作弊直接拿出的材料才能合成，自己合成的材料无法用于合成。
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
能够自动化星能聚合器，或者有其余的共振宝石配方
**截图**
![2020-02-17_16 19 47](https://user-images.githubusercontent.com/61138880/74635769-a64efb80-51a1-11ea-9e85-43ba99204670.png)
![2020-02-17_16 19 49](https://user-images.githubusercontent.com/61138880/74635772-a8b15580-51a1-11ea-8bab-891b3114587f.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：8G
 - Java版本：
- 整合包版本*：1.3.3

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
- 关于共振宝石，不清楚阁下对于“大量”一词的定义是指“客观上很多的量”还是“能让我嫌麻烦的量”。请尽早做出转化桌与灵气附着装置并探寻赚取EMC的途径；
- 引用到更替之星和贤者之石的配方，收到过极少数偶现的反馈，可能由于某些情况下拓展工作台对于带NBT的物品兼容性较差，暂无解决方案。

**Comment by starsforest** [comment]
好吧，我确实只关注了灵气附着装置需要到神龙级别却没发现龙芯是有EMC的，那整条路确实可以接受多了，这是我的错。不过，在我的存档中用AE自动合成聚合粘土仍然会消耗粘土花，这是bug吗，这让用下界之星刷EMC有点麻烦，虽然终极锭应该会比它好多了。

**Comment by ChromaPIE** [comment]
> 好吧，我确实只关注了灵气附着装置需要到神龙级别却没发现龙芯是有EMC的，那整条路确实可以接受多了，这是我的错。不过，在我的存档中用AE自动合成聚合粘土仍然会消耗粘土花，这是bug吗，这让用下界之星刷EMC有点麻烦，虽然终极锭应该会比它好多了。

仍然非常推荐使用终极锭来赚取EMC，但使用下界之星交换EMC的操作过于清奇。等价交换的继电器是开放使用的。在Alpha阶段中期，想必阁下AE中各种矿物储量已经相当巨大，非常推荐处理矿机中诸如钛、铱、铂、绿宝石、蓝宝石、红宝石、钻石、钨等已无大量需求的矿物，配合六级卡莱恩能量之星，来日常地，自动化地获取EMC。别忘了把待抛售的矿物锭在转化桌中存档以防万一。祝游戏愉快。
