### ISSUE TITLE
[BUG]根源魔法和自然灵气翻译丢失

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#358]
**描述BUG**
RT，同时箱子里的物品也丢失了翻译，在1.3.3中正常。
**如何重现**
目前只发现用1.3.4中打开1.3.3的存档，新档未测试
**原本期望**
若无此BUG，原本你期待发生什么？
和原来一样是中文状态
**截图**
![批注 2020-02-19 110213](https://user-images.githubusercontent.com/11871061/74798141-e9c37a00-5307-11ea-8b81-d0ad2d508a84.png)
![批注 2020-02-19 110244](https://user-images.githubusercontent.com/11871061/74798145-eb8d3d80-5307-11ea-85f1-6eb2b3a05c47.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.3.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
汉化资源包特性，重启游戏即可
