### ISSUE TITLE
[BUG]物品转运器贴图丢失

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#359]
**描述BUG**
RT，在1.3.3中正常
**如何重现**
在1.3.4中打开1.3.3的存档，新档未测试
**原本期望**
若无此BUG，原本你期待发生什么？
和原来一样贴图正常
**截图**
![批注 2020-02-19 110143](https://user-images.githubusercontent.com/11871061/74798228-25f6da80-5308-11ea-8fb2-57ee0ea70ecf.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.3.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
遗留BUG，自0.5Beta起就有，模组问题，请在此报告：https://github.com/Chicken-Bones/Translocators

**Comment by sjdhome** [comment]
可是1.3.3和以前的版本并没有问题啊

**Comment by dong031001** [comment]
> 可是1.3.3和以前的版本并没有问题啊

你制作一个放到世界中就正常了。这个问题一直都有，只是有几率不触发而已，玄学。
