### ISSUE TITLE
[BUG]脉络附魔无法作用于赛特斯石英矿石

### ISSUE THREAD

**Issue by 1870332922** [ET-Team/EnigTech2#361]
脉络附魔无法作用于AE2的赛特斯石英矿石和充能的赛特斯石英矿石
已确定 ET2 - 1.3.1 、1.3.4 均有此问题

**Comment by dong031001** [comment]
有样板都不用...

**Comment by dong031001** [comment]
已向Veining repo发送Pull Request https://github.com/arlyon/veining/pull/24 且注意到作者两年内无更新仓库，发送了一封提醒邮件：

> Hello Arlyon,
> 
> I got this email address from your GitHub page, and it seems that you haven’t update your mod in a while, 2 years actually, and I am not sure whether you can receive the notification from GitHub, therefore I am sending this email in order to notice you about a pull request I just made. I really enjoy your mod, so I want to include it in my modpack and make it as compatible with other mods as possible; therefore, I hope you can add support to AE2, which is also a great mod.
> 
> Best,
> Shear

**Comment by ChromaPIE** [comment]
EnigTech2整合包凭什么要对下属所有mod负责？发邮件是情分，不予受理是本分。

**Comment by ChromaPIE** [comment]
# 整合包作者≠整合包中所有MOD的作者

**Comment by dong031001** [comment]
> # 整合包作者≠整合包中所有MOD的作者

实际上为赛特斯石英水晶加入一个gemCertusQuartz即可解决问题，已在本地修复。

**Comment by 1870332922** [comment]
> > # 整合包作者≠整合包中所有MOD的作者
> 
> 实际上为赛特斯石英水晶加入一个gemCertusQuartz即可解决问题，已在本地修复。

感谢您在veining模组的github上提交的代码修改建议，已自行重编译源代码文件，该问题现已解决。

**Comment by 1870332922** [comment]
> EnigTech2整合包凭什么要对下属所有mod负责？发邮件是情分，不予受理是本分。

对对对，你说得对。但是你改的标题就很欠揍啊“
 [典例 - 非整合包范畴执意反馈至整合包GitHub仓库]脉络附魔无法作用于赛特斯石英矿石” ]

典例？？这个就算了。
执意？你这是什么意思？
什么叫执意？意思是坚持自己的意愿。这个词放在你设置的title里，我读出了贬义。
整合包里绝大部分mod我都没玩过，我都不知道是哪个mod的问题，当然反馈给你们了。你们不受理的话，至少告诉我哪个mod的问题，我又不是不能亲自反馈，没有也谈不上执意。

dong031001 从前到后一直在帮我的忙，帮我改模板，帮我发邮件，修改代码，我非常感激他。
瞧瞧你这德行，不受理就算了，把这标题改的像你这人一样贱。

**Comment by ChromaPIE** [comment]
> > EnigTech2整合包凭什么要对下属所有mod负责？发邮件是情分，不予受理是本分。
> 
> 对对对，你说得对。但是你改的标题就很欠揍啊“
> [典例 - 非整合包范畴执意反馈至整合包GitHub仓库]脉络附魔无法作用于赛特斯石英矿石” ]
> 
> 典例？？这个就算了。
> 执意？你这是什么意思？
> 什么叫执意？意思是坚持自己的意愿。这个词放在你设置的title里，我读出了贬义。
> 整合包里绝大部分mod我都没玩过，我都不知道是哪个mod的问题，当然反馈给你们了。你们不受理的话，至少告诉我哪个mod的问题，我又不是不能亲自反馈，没有也谈不上执意。
> 
> dong031001 从前到后一直在帮我的忙，帮我改模板，帮我发邮件，修改代码，我非常感激他。
> 瞧瞧你这德行，不受理就算了，把这标题改的像你这人一样贱。

你没有必要在这儿张牙舞爪的，大放厥词并不会对我造成什么影响。你气得不轻，我的目的达到了。捧一个踩一个的伎俩初中毕业之后就没怎么见过，估计倒是阁下身边这样的人不少，搞的自己被同化了。奉劝一句，别把无知当武器。把mod的问题反馈到整合包这边来已经让我看到你的无知了，现在又看到了一次。暴露出来让别人看到了，骂，属于正常；帮，是出于人道。巧了，我天生贱骨头，天生看不惯拿着无知向别人报喜的。感激dong031001无可厚非，搁这儿怼我怼一大堆，就纯属是活该被人贬了还糊在人脸上炸火星子。在我跟你一样无知的时候我选择的是闭门造车，所以我从来没有过阁下这种黄口孺子四处乱窜，被人教训了还活生闷气当网络肖邦的体验。有“不堪的德行”和“文如其人一样贱”的人，现在是你玩的包的联合作者，实属讽刺。黄鳝人好，唱红脸；我人贱，唱得是白脸。辞或伤人，如被刺中，不胜荣幸。

**Comment by 1870332922** [comment]
> > > EnigTech2整合包凭什么要对下属所有mod负责？发邮件是情分，不予受理是本分。
> > 
> > 
> > 对对对，你说得对。但是你改的标题就很欠揍啊“
> > [典例 - 非整合包范畴执意反馈至整合包GitHub仓库]脉络附魔无法作用于赛特斯石英矿石” ]
> > 典例？？这个就算了。
> > 执意？你这是什么意思？
> > 什么叫执意？意思是坚持自己的意愿。这个词放在你设置的title里，我读出了贬义。
> > 整合包里绝大部分mod我都没玩过，我都不知道是哪个mod的问题，当然反馈给你们了。你们不受理的话，至少告诉我哪个mod的问题，我又不是不能亲自反馈，没有也谈不上执意。
> > dong031001 从前到后一直在帮我的忙，帮我改模板，帮我发邮件，修改代码，我非常感激他。
> > 瞧瞧你这德行，不受理就算了，把这标题改的像你这人一样贱。
> 
> 你没有必要在这儿张牙舞爪的，大放厥词并不会对我造成什么影响。你气得不轻，我的目的达到了。捧一个踩一个的伎俩初中毕业之后就没怎么见过，估计倒是阁下身边这样的人不少，搞的自己被同化了。奉劝一句，别把无知当武器。把mod的问题反馈到整合包这边来已经让我看到你的无知了，现在又看到了一次。暴露出来让别人看到了，骂，属于正常；帮，是出于人道。巧了，我天生贱骨头，天生看不惯拿着无知向别人报喜的。感激dong031001无可厚非，搁这儿怼我怼一大堆，就纯属是活该被人贬了还糊在人脸上炸火星子。在我跟你一样无知的时候我选择的是闭门造车，所以我从来没有过阁下这种黄口孺子四处乱窜，被人教训了还活生闷气当网络肖邦的体验。有“不堪的德行”和“文如其人一样贱”的人，现在是你玩的包的联合作者，实属讽刺。黄鳝人好，唱红脸；我人贱，唱得是白脸。辞或伤人，如被刺中，不胜荣幸。

我有大放厥词吗？除了最后一句话说得重了点。
我也算了解一点你的为人了：过度反应，言过其实，脾气不好，嘴臭（我昨天没刷牙，刚才闻了下的确也挺臭的，啊哈哈）。
不好意思，我没有被刺中，我现在像是在看猴子表演一样笑着读你的评论。
就这样吧。我不会浪费时间和你斗嘴了，那是在浪费我自己的生命，脏了我的键盘。

**Comment by dong031001** [comment]
@1870332922 @ChromaPIE 没有任何必要在这里吵起来。报告者在此之前并没有抛过任何Issue，谈不上执意，以后遇到模组问题直接将对应repo链接发上去就好，针锋相对没有任何意义。
