### ISSUE TITLE
[其他]建议：优化TPS

### ISSUE THREAD

**Issue by 1870332922** [ET-Team/EnigTech2#367]
建议后期ET2更新  新增Mod：
Tick Dynamic 【优化TPS】

缘由：
和朋友玩到阶段四，游戏逐渐随着发展的深入开始卡顿。
使用整合包自带的LagGoggles分析发现问题：余烬mod的流体管道，以及植魔导致TPS过低。
实测安装该mod可以解决问题

**Comment by dong031001** [comment]
模组尝试过，但副作用非常大：随着服务器运行时间增加，机器TPS会降低到一个难以接受的范围，甚至达到1-3TPS（主世界），不推荐使用。

**Comment by 1870332922** [comment]
> 模组尝试过，但副作用非常大：随着服务器运行时间增加，机器TPS会降低到一个难以接受的范围，甚至达到1-3TPS（主世界），不推荐使用。

"随着服务器运行时间增加" ，这个运行时间指的是持续运行时间还是累计运行时间？

**Comment by dong031001** [comment]
> > 模组尝试过，但副作用非常大：随着服务器运行时间增加，机器TPS会降低到一个难以接受的范围，甚至达到1-3TPS（主世界），不推荐使用。
> 
> "随着服务器运行时间增加" ，这个运行时间指的是持续运行时间还是累计运行时间？

持续运行时间

**Comment by 1870332922** [comment]
> > > 模组尝试过，但副作用非常大：随着服务器运行时间增加，机器TPS会降低到一个难以接受的范围，甚至达到1-3TPS（主世界），不推荐使用。
> > 
> > 
> > "随着服务器运行时间增加" ，这个运行时间指的是持续运行时间还是累计运行时间？
> 
> 持续运行时间

好的，感谢告知。我和朋友就两人玩，偶尔几个小时重启一次服务器就行了，问题不大
