### ISSUE TITLE
[待办] 隐藏植物魔法机巧箱

### ISSUE THREAD

**Issue by passage2016** [ET-Team/EnigTech2#375]
### 以下为原反馈内容：
----
**描述BUG**
植物魔法机巧箱按照合成表输入物品后物品消失
**如何重现**
漏斗连接机巧箱，将物品按顺序放入漏斗，无物品输出，且机巧箱内物品消失
**原本期望**
若无此BUG，原本你期待发生什么？
自动化制造
**截图**

**运行环境（请越详细越好）:**
服务端
 - 操作系统*：
 - 运行内存：4G
 - Java版本：
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
- 整合包版本*：
1.3.4
**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
整合包版本？

**Comment by passage2016** [comment]
1.3.4

**Comment by dong031001** [comment]
> 1.3.4

机巧箱设计无法使用，下个版本会隐藏这个物品

**Comment by ChromaPIE** [comment]
> > 1.3.4
> 
> 机巧箱设计无法使用，下个版本会隐藏这个物品

packagestage问题已发现解决方案（尚未实测可否应用于机巧箱，理论可行），是否确定考虑隐藏机巧箱？若留存考虑，将尝试将机巧箱加入packagestage并实测。

**Comment by dong031001** [comment]
> > > 1.3.4
> > 
> > 
> > 机巧箱设计无法使用，下个版本会隐藏这个物品
> 
> packagestage问题已发现解决方案（尚未实测可否应用于机巧箱，理论可行），是否确定考虑隐藏机巧箱？若留存考虑，将尝试将机巧箱加入packagestage并实测。

机巧箱在现有条件下没有意义了。

**Comment by ChromaPIE** [comment]
机巧箱已在明早会推送的pr中被隐藏

**Comment by ChromaPIE** [comment]
第三阶段对任何所谓的自动化合成均无刚需。此issue就此告讫。

**Comment by dong031001** [comment]
> > > > > 1.3.4
> > > > 
> > > > 
> > > > 机巧箱设计无法使用，下个版本会隐藏这个物品
> > > 
> > > 
> > > packagestage问题已发现解决方案（尚未实测可否应用于机巧箱，理论可行），是否确定考虑隐藏机巧箱？若留存考虑，将尝试将机巧箱加入packagestage并实测。
> > 
> > 
> > 机巧箱在现有条件下没有意义了。
> 
> 可以在第三阶段开启自动化合成

请用自然灵气合成台。
