### ISSUE TITLE
[BUG]战斗中玩家死亡后服务器崩溃墓碑未出现导致物品丢失

### ISSUE THREAD

**Issue by passage2016** [ET-Team/EnigTech2#377]
**描述BUG**
战斗中玩家死亡后服务器崩溃重启后墓碑未出现导致物品丢失
**如何重现**
如上
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:** 
服务端

操作系统*：ubuntu
运行内存：4G
Java版本：
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
整合包版本*：
1.3.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

以下为服务器开服以来全部后台日志，除一次手动关服其余均为此问题导致，定位可在文件内搜索 open.sh定位断点
[http://207.148.124.9/MC/screenlog.0](url)

**Comment by ChromaPIE** [comment]
请至墓碑模组（Corail's Tombstone）的GitHub页面使用英语进行反馈

**Comment by passage2016** [comment]
ok thanks [https://github.com/Corail31/tombstone_lite/issues/138](url)
