### ISSUE TITLE
[BUG] 战斗中玩家死亡后服务器崩溃重启后墓碑未出现导致物品丢失[更新]

### ISSUE THREAD

**Issue by passage2016** [ET-Team/EnigTech2#378]
That's the reply for me and I hope you can use the new version of that next time, THX

Hello, please try to follow the version patch notes, as it's really rare when i add a bug in my version, and it's the case for 3.6.7 due to a mistake by backporting some changes from 1.15.2.
It's indeed fixed in 3.6.8 and if you didn't see : the version is also archived on curseForge...

[https://github.com/Corail31/tombstone_lite/issues/138](url)
描述BUG
战斗中玩家死亡后服务器崩溃重启后墓碑未出现导致物品丢失
如何重现
如上
原本期望
若无此BUG，原本你期待发生什么？

截图

运行环境（请越详细越好）:
服务端

操作系统*：ubuntu
运行内存：4G
Java版本：
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
整合包版本*：
1.3.4

错误报告
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
请耐心等待模组方回复
