### ISSUE TITLE
[BUG]流体漏斗尝试导出蒸汽导致存档崩溃死档

### ISSUE THREAD

**Issue by cqx0792** [ET-Team/EnigTech2#382]
**描述BUG**
我调试微型蒸汽锅炉产气体系时尝试使用流体漏斗像处理多余的杂酚油那样销毁多余蒸汽，然后流体漏斗一接就退出服务端，并进入存档后的瞬间会秒崩回主菜单。
**如何重现**
在装有蒸汽的EIO的流体储罐下直接接流体漏斗
**原本期望**
蒸汽被流体漏斗正常导出游戏正常进行，或流体漏斗不识别蒸汽无法导出但游戏正常进行。

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：8G
 - Java版本：open9java 8.0.212.03
- 整合包版本*：1.3.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
请至流体漏斗（Flopper）或余烬复刻版（Embers Rekindled）的GitHub页面使用英语反馈如上问题。
