### ISSUE TITLE
[BUG] 辉耀工作台吞物品 复现

### ISSUE THREAD

**Issue by passage2016** [ET-Team/EnigTech2#383]
试图制作铁齿轮及箱子，物品消失经搜索发现出现过此类问题
问题复现： [https://github.com/ET-Team/EnigTech2/issues/298](url)
运行环境（请越详细越好）:
服务端

操作系统*：
运行内存：4G
Java版本：
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
整合包版本*：
1.3.4
[https://github.com/ET-Team/EnigTech2/issues/298](url)

**Comment by ChromaPIE** [comment]
开发版已修复
