### ISSUE TITLE
[建议]开启服务器多线程，解决TPS过低

### ISSUE THREAD

**Issue by 1870332922** [ET-Team/EnigTech2#386]
https://www.mcbbs.net/thread-809680-1-1.html
我参照这个帖子，在server.properties文件里添加了一行参数 useSMPAPI=true ，开启了服务器的多线程支持。主世界TPS由之前的5-9提升到17-19，强烈建议在下个版本的服务器端里添加该参数。
放图：
之前【CPU】：
![TIM截图20200304225314](https://user-images.githubusercontent.com/53111664/75892435-47a9a300-5e6c-11ea-8c80-d2e3c793ccd9.png)
之前【TPS】：
![TIM图片20200304230056](https://user-images.githubusercontent.com/53111664/75892463-5001de00-5e6c-11ea-8585-8e47fc3800f2.png)
之后【CPU】：
![TIM截图20200304230817](https://user-images.githubusercontent.com/53111664/75893096-462caa80-5e6d-11ea-8b1c-ec0634eb209c.png)
之后【TPS】：
![TIM截图20200304225133](https://user-images.githubusercontent.com/53111664/75893140-56448a00-5e6d-11ea-9549-2c889ef06adb.png)

**Comment by dong031001** [comment]
此应由用户决定是否开启。服务端不会附带server.properties
