### ISSUE TITLE
[其他]建议ban掉热力强化弓

### ISSUE THREAD

**Issue by cqx0792** [ET-Team/EnigTech2#398]
玩到第4阶段后期突然发现一直用的热力强化弓太强了，平时秒杀小怪看不出来，但试着打了一次盖亚2就发现了新天地，强化弓特有的万箭4加力量5的钻石强化弓，身上没有任何其他伤害buff，箭用的也是野木箭袋伤害似乎比普通箭还低，这样拉满弓正好3发秒盖亚2，伤害正好能跳过最麻烦的阶段2十几秒内解决战斗，难度大幅下降。战斗时间还没召唤时间长，普通弓伤害低寂静宝石弓无法附魔万箭都没办法跳过阶段2速刷，而掉落物品别的不说就那些高级符文就很赚了，感觉符文压印机和复杂的炼金台合成都不用了。而召唤用的盖亚魂锭成本又特别低，魂能自给自足，唯一的成本就是那点电和黎明石。不过虽然感觉有点影响平衡但看4阶段似乎没有什么太消耗高级符文的进度，后面还没开也不知道具体情况所以只是小小的建议一下。

**Comment by ChromaPIE** [comment]
请阁下明确ET2整合包的定位：**大型魔改科魔整合包**，而非**生存冒险RPG整合包**。

**Comment by cqx0792** [comment]
正因如此，个人感觉在一个科魔整合包中战斗获取材料的收益比科技线高很多是件很奇怪的事，加上盖亚魂锭的低造价阶段4就能安全速刷盖亚2获取大量高级符文，使得科魔路线复杂昂贵的炼金台合成高级符文显得多余而毫无意义。

**Comment by ChromaPIE** [comment]
ban热力强化弓无可能性，下一版本会酌情考虑修改盖亚生命值/改难热力弓配方。issue终止。
