### ISSUE TITLE
[BUG]服务器玩家被持有钻石剑的僵尸秒杀后服务器崩溃

### ISSUE THREAD

**Issue by GreatCoffee** [ET-Team/EnigTech2#400]
**描述BUG** 如题。服务器经历了一次崩溃，据玩家描述，其被一只手持钻石剑的僵尸攻击并被秒杀后服务器当时崩溃。

**如何重现** 未知

**原本期望** 玩家正常被秒杀，服务器不崩溃

**截图** 无

**运行环境（请越详细越好）:** 
服务端架设在一台性能一般的面板服上，配置未知。Java 8。

**错误报告**
过长，请移步 https://pastebin.com/1scJ6hjB

**Comment by dong031001** [comment]
Corail Tombstone模组问题，已经在1.4.0更新模组解决，你也可以自行下载新版本解决。
