### ISSUE TITLE
[BUG]设置按键绑定jei时候左键点击只有再次左键，游戏无限崩溃

### ISSUE THREAD

**Issue by Zzzzzzouhang** [ET-Team/EnigTech2#404]
**描述BUG**
设置按键绑定jei时候左键点击只有再次左键，游戏无限崩溃，再次启动游戏一样无限崩溃
**如何重现**

**原本期望**
修改按键

**截图**
![6I)UM_9MT_$~8`VLH2Z8{(L](https://user-images.githubusercontent.com/61148270/76696537-9acef180-66c7-11ea-961f-cefe6c91ea82.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10 64位专业版
 - 运行内存：8G，分配游戏内存4G
 - Java版本：jdk1.8.0.202
- 整合包版本*：1.3.4
[crash-2020-03-15_14.10.30-client.txt](https://github.com/ET-Team/EnigTech2/files/4333842/crash-2020-03-15_14.10.30-client.txt)

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by Zzzzzzouhang** [comment]
崩溃报告https://paste.ubuntu.com/p/rxWr6Zzngh/

**Comment by Zzzzzzouhang** [comment]
![asdf](https://user-images.githubusercontent.com/61148270/76696938-d4096080-66cb-11ea-8a68-8552c24db505.gif)
根据我的测试无论是左键还是右键都会导致游戏无限崩溃，群里大佬提示删options文件就可以进游戏了

**Comment by ChromaPIE** [comment]
请将所有问题反馈至Just Enough Items的GitHub反馈页面。
