### ISSUE TITLE
English translation bug[其他]

### ISSUE THREAD

**Issue by tuc56** [ET-Team/EnigTech2#405]
The advancement "Sand, Now at disposal" Should be renamed "Snad, Now at disposal", because the advancement requires you to get snad.

**Comment by dong031001** [comment]
I don't see anything wrong with that... Once you get snad, sand is rather useless in terms of planting cactus and sugar canes.

**Comment by tuc56** [comment]
sorry if i didn't make it clear, the advancement doesn't mention snad, so you have to guess what it is talking about. not good for someone who doesn't know about snad.

**Comment by ChromaPIE** [comment]
Description successfully improved. Thanks for reporting.

**Comment by tuc56** [comment]
You are welcome! Glad I could help in development of thin awesome pack!
