### ISSUE TITLE
[BUG]局域网多人游戏主机死亡需要其他玩家退出才可以复活

### ISSUE THREAD

**Issue by KieMor** [ET-Team/EnigTech2#406]
**描述BUG**
在局域网多人游戏中主机死亡需要其他玩家退出才可以复活 只尝试过双人游戏
**如何重现**
死亡
**原本期望**
若无此BUG，原本你期待发生什么？
直接点击即可复活
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 家庭版 64位
 - 运行内存：
 - Java版本：
- 整合包版本*：v1.3.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
联机请用服务端。局域网联机可能出现不可预知的问题。
