### ISSUE TITLE
[崩溃]游戏崩溃

### ISSUE THREAD

**Issue by CsyBarry** [ET-Team/EnigTech2#411]
**描述BUG**
当我使用光影时游戏会直接闪退，更新1.3.5前并未出现过该问题，甚至刚更新1.3.5时曾带光影成功运行过
**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10
 - 运行内存：16.00G（分配8G）
 - Java版本：Java8
- 整合包版本*：1.3.5
**错误报告**
https://paste.ubuntu.com/p/ftwcdhYQ96/
这里列出部分错误
![批注 2020-03-26 085247](https://user-images.githubusercontent.com/60415944/77600301-733b1d00-6f42-11ea-84e2-233e1f61f998.png)
![批注 2020-03-26 085010](https://user-images.githubusercontent.com/60415944/77600303-76cea400-6f42-11ea-96cb-4cc9ba24aade.png)
![批注 2020-03-26 085824](https://user-images.githubusercontent.com/60415944/77600306-7afac180-6f42-11ea-9ac6-0745907d79a7.png)
![批注 2020-03-26 085656](https://user-images.githubusercontent.com/60415944/77600310-7f26df00-6f42-11ea-8d48-fe52f3f6571c.png)
![批注 2020-03-26 085408](https://user-images.githubusercontent.com/60415944/77600322-88b04700-6f42-11ea-8284-f1fcc9a5efb0.png)

**Comment by dong031001** [comment]
内存溢出，请分配更多内存。

**Comment by CsyBarry** [comment]
反复尝试改大内存分配均无法启动，甚至无法完成游戏加载
另外出现模组崩溃
https://paste.ubuntu.com/p/cDsTN4Nzwg/
![image](https://user-images.githubusercontent.com/60415944/77607361-0b420200-6f55-11ea-9e67-78d9c8ecfa13.png)

**Comment by dong031001** [comment]
> 反复尝试改大内存分配均无法启动，甚至无法完成游戏加载
> 另外出现模组崩溃
> https://paste.ubuntu.com/p/cDsTN4Nzwg/
> ![image](https://user-images.githubusercontent.com/60415944/77607361-0b420200-6f55-11ea-9e67-78d9c8ecfa13.png)

尝试删除Caliper模组？
