### ISSUE TITLE
[BUG]服务器崩溃

### ISSUE THREAD

**Issue by TiaoShu1126** [ET-Team/EnigTech2#415]
服务器崩溃
[crash-2020-03-30_18.51.42-server.txt](https://github.com/ET-Team/EnigTech2/files/4402329/crash-2020-03-30_18.51.42-server.txt)

**Comment by 1870332922** [comment]
请用记事本打开服务器里的server.properties文件
将max-tick-time=60000
更改为max-tick-time=-1

**Comment by dong031001** [comment]
服务器过载。请更换配置或调整最大Tick事件
