### ISSUE TITLE
[其他]建议禁止寂静宝石中的增强附魔，目前1.12.2版本没有任何用

### ISSUE THREAD

**Issue by Zzzzzzouhang** [ET-Team/EnigTech2#418]
![SFK7Q2RK}MOSQFTPK}P_U0P](https://user-images.githubusercontent.com/61148270/78775710-40c10380-79c9-11ea-944d-4a898a174c51.png)
目前没有任何用处却占着一个附魔的位置，建议ban掉。

**Comment by ChromaPIE** [comment]
**缺乏配置项，无法禁用。**
