### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 18263212936** [ET-Team/EnigTech2#422]
1.3.5版本做完一阶段 二阶段进度不开启

**运行环境（请越详细越好）:**
 - 操作系统*：windos10
 - 运行内存：6000Mb
 - Java版本：8
- 整合包版本*：1.3.5
![14：25](https://user-images.githubusercontent.com/42309965/79421807-2e108500-7fee-11ea-8852-4951855b7d8f.png)

**Comment by ChromaPIE** [comment]
有尝试过把智慧药剂拿在主手右键吗？

**Comment by 18263212936** [comment]
> 有尝试过把智慧药剂拿在主手右键吗？

是主手右键，而且试了不止一次

**Comment by 18263212936** [comment]
> 有尝试过把智慧药剂拿在主手右键吗？

之前玩其他版本没有出现这种情况

**Comment by dong031001** [comment]
无法重现
