### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lddd99** [ET-Team/EnigTech2#424]
**可能是这么设计的但是是个问题**
JEI原版配方都查不到了，例如剪刀和火把明明是已经解锁了。却不在jei列表中，只能在铁锭U键里面找到剪刀

**如何重现**

**原本期望“”
能在JEI列表中显示能使用的原版配方

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
请详细填写运行环境。
