### ISSUE TITLE
[BUG]野生根茎无法正常打草获得

### ISSUE THREAD

**Issue by zhou960405** [ET-Team/EnigTech2#435]
**描述BUG**
野生根茎无法正常打草获得
**如何重现**
尝试着开了3个存档，第一个存档打了十分钟草一个没掉，第二个就掉了一个，第三个也是一个没掉，无法继续ROOTS进度
**原本期望**
若无此BUG，原本你期待发生什么？
获得野生根茎掉落
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：WIN10
 - 运行内存：10G
 - Java版本：1.8.0_231
- 整合包版本*：1.4.0带DLC

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
既然你第二次掉了一个 为何不种下？能用BUG代辞脸黑吗？
