### ISSUE TITLE
[待办]更高等级装配机与蚀刻机

### ISSUE THREAD

**Issue by dong031001** [ET-Team/EnigTech2#436]

**Comment by dong031001** [comment]
@sun-wilhelm 
### 集成装配机MK1(intergrated_assembly_mk1)需求
1. 拥有蒸汽装配机和智能装配装置的一切配方
2. 速度在基础上提高20%左右
3. 机器所用建材可以跟智能装配装置部分重叠以减少材料需求
4. 机器在阶段五后期可用
5. 拥有可变大小物品输入/输出仓

#### 集成装配机MK2(intergrated_assembly_mk1)需求
1. 在MK1基础上再提高40%左右处理速度
2. 机器可以视为MK1版本的改造，大部分建材重叠并可以直接在MK1基础上改建
3. 部分基础材料的配方可以酌情提高产出
4. 大幅降低耗能
5. 需要图纸建造（图纸将会在遗迹更新的宝箱中获得）

### 高能激光蚀刻机(razer)需求
1. 继承余烬能激光蚀刻机的所有配方
2. 使用MEK激光代替灰烬能量
3. 速度可大幅提升
4. 六阶初期可以制造（可以使用一，二级结构方块搭建）
5. 需要图纸建造（同上）

###

**Comment by sun-wilhelm** [comment]
@dong031001 这个PR已经可以merge了。
