### ISSUE TITLE
[BUG]新加入的附魔导致破坏平衡

### ISSUE THREAD

**Issue by baojianan** [ET-Team/EnigTech2#438]
新加入的Random 附魔中，有一个叫随机奖励（Randomness）的附魔，导致破坏平衡。
该附魔导致开采任意方块时会掉落随机物品（可兼容其他mod），每一级增加一个物品。
本人已经10小时毕业---打了7小时的草

**Comment by ChromaPIE** [comment]
该附魔早已禁止附魔台附出，唯一获取方式为战利品箱获取，开发版将会禁用并会随1.4.1更新。在探明该附魔具体效用后正确做法是**立即停止使用**。

**Comment by baojianan** [comment]
本人是村民那里买到的

**Comment by baojianan** [comment]
> 该附魔早已禁止附魔台附出，唯一获取方式为战利品箱获取，开发版将会禁用并会随1.4.1更新。在探明该附魔具体效用后正确做法是**立即停止使用**。

本人是村民那里买到的

**Comment by 10935336** [comment]
村民交易就可以买到，对服务器威胁极大。

> 在探明该附魔具体效用后正确做法是立即停止使用。

我认为这不能算是解决方案

**Comment by ChromaPIE** [comment]
我也认为这不能算是解决方案，所以我在回复里写了这样一句话并且在9e74ebc里实现了：

> 开发版将会禁用并会随1.4.1更新

如果您没有看到，我**深表遗憾**。

**Comment by 10935336** [comment]
看到了，但是未解决的问题真的适合close吗。

**Comment by dong031001** [comment]
> ~看到了，但是未解决的问题真的适合close吗。~
> 抱歉没看到9e74ebc，但正确的close方式应该是
> 
> > https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
> 
> 否则容易让人认为问题并未解决，但是issue却关闭了

![QQ截图20200513184525](https://user-images.githubusercontent.com/30747164/81803254-fdb6fa80-9549-11ea-8d6c-0f97437033b5.png)
