### ISSUE TITLE
法术收容袋复制物品[BUG]

### ISSUE THREAD

**Issue by baojianan** [ET-Team/EnigTech2#441]
1. 

- 

**描述BUG**
2个法术收容袋能复制物品
**如何重现**
东西放入1号位收容袋，丢出瞬间右键打开，把2号位收容袋放入1号位，取出物品，捡回丢出的袋子
完成复制。

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
Replicate of https://github.com/MysticMods/Roots/issues/492
