### ISSUE TITLE
[BUG]炽铁块不能还原成炽热铁锭

### ISSUE THREAD

**Issue by bwmgd** [ET-Team/EnigTech2#442]
描述BUG

如何重现

原本期望
若无此BUG，原本你期待发生什么？

运行环境（请越详细越好）:

操作系统*：
运行内存：
Java版本：
整合包版本*：

**Comment by dong031001** [comment]
有模板不用？

**Comment by ChromaPIE** [comment]
已受理。开发版已修复。请在即将发布的1.4.1版本中使用压缩抽屉拆解炽铁块。
