### ISSUE TITLE
[BUG]1.3.4直升至1.4.0版本,服务器无法启动

### ISSUE THREAD

**Issue by ShiraGawaAnri** [ET-Team/EnigTech2#443]
**描述BUG**
以1.3.4为基础的服务器的存档
下载1.4.0版服务器并解压释放到新文件夹
复制1.3.4版存档至1.4.0下
启动服务器后

[21:57:44] [Server thread/INFO] [FML]: Using fml.queryResult confirm to answer the following query:
Forge Mod Loader detected missing registry entries.

There are 1 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:enchantments:
    endercore:autosmelt

随后无论是在参数中加入-Dfml.queryResult=confirm
还是在控制台 /fml confirm
均会在最后阶段弹出服务器关闭等信息
详见附件。

**如何重现**
如果需要可邮件存档

**原本期望**
保持存档升级并正常运行1.4.0

**截图**
![QQ图片20200515221907](https://user-images.githubusercontent.com/17354188/82060537-1f56e400-96fa-11ea-8809-cc46c5211a03.png)

**运行环境（请越详细越好）:**
 - 操作系统*： Windows Server 2012 (amd64) version 6.2
 - 运行内存：32GB
 - Java版本：1.8.0_241
- 整合包版本*：1.3.4(正常运行)->1.4.0(出现Bug)

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-05-15_22.00.32-server.txt](https://github.com/ET-Team/EnigTech2/files/4634878/crash-2020-05-15_22.00.32-server.txt)

**Comment by ShiraGawaAnri** [comment]
不知道是不是提交至这边，如有不正确的地方，请指正

**Comment by dong031001** [comment]
尝试过回档吗？存档移回至1.3.4版本问题持续吗？

**Comment by ShiraGawaAnri** [comment]
1.回档无效
2.经过/fml confirm操作后的存档移动到旧版(1.3.4) 存档内容正常,服务器正常启动

目前找到原因
=================================
这个是1.3.4使用的server配置
spawn-protection=16
max-tick-time=60000
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25566
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=false
max-build-height=256
level-seed=cifangshabi250
prevent-proxy-connections=false
use-native-transport=true
enable-rcon=false

=================================
1.4.0 server配置(默认生成)
#Minecraft server properties
#Sat May 16 12:52:19 CST 2020
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
prevent-proxy-connections=false
server-port=25566
max-world-size=29999984
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=
network-compression-threshold=256
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
snooper-enabled=true
resource-pack-sha1=
online-mode=true
resource-pack=
pvp=true
difficulty=1
enable-command-block=false
player-idle-timeout=0
gamemode=0
max-players=20
max-tick-time=60000
spawn-monsters=true
generate-structures=true
view-distance=10
motd=A Minecraft Server
=================================
把1.3.4的配置复制(复制后修改了端口 同时关掉了1.3.4防止影响)到1.4.0版配合1.3.4的存档则报错
但是用1.4.0生成默认的server配置(修改了端口)则不会报错
不知道是哪一项出了问题

**Comment by dong031001** [comment]
> 1.回档无效
> 2.经过/fml confirm操作后的存档移动到旧版(1.3.4) 存档内容正常,服务器正常启动
> 
> # 目前找到原因
> 这个是1.3.4使用的server配置
> spawn-protection=16
> max-tick-time=60000
> generator-settings=
> force-gamemode=false
> allow-nether=true
> gamemode=0
> broadcast-console-to-ops=true
> enable-query=false
> player-idle-timeout=0
> difficulty=1
> spawn-monsters=true
> op-permission-level=4
> pvp=true
> snooper-enabled=true
> level-type=DEFAULT
> hardcore=false
> enable-command-block=false
> max-players=20
> network-compression-threshold=256
> resource-pack-sha1=
> max-world-size=29999984
> server-port=25566
> server-ip=
> spawn-npcs=true
> allow-flight=true
> level-name=world
> view-distance=10
> resource-pack=
> spawn-animals=true
> white-list=false
> generate-structures=true
> online-mode=false
> max-build-height=256
> level-seed=cifangshabi250
> prevent-proxy-connections=false
> use-native-transport=true
> enable-rcon=false
> 
> =================================
> 1.4.0 server配置(默认生成)
> #Minecraft server properties
> #Sat May 16 12:52:19 CST 2020
> generator-settings=
> op-permission-level=4
> allow-nether=true
> level-name=world
> enable-query=false
> allow-flight=false
> prevent-proxy-connections=false
> server-port=25566
> max-world-size=29999984
> level-type=DEFAULT
> enable-rcon=false
> force-gamemode=false
> level-seed=
> server-ip=
> network-compression-threshold=256
> max-build-height=256
> spawn-npcs=true
> white-list=false
> spawn-animals=true
> snooper-enabled=true
> resource-pack-sha1=
> online-mode=true
> resource-pack=
> pvp=true
> difficulty=1
> enable-command-block=false
> player-idle-timeout=0
> gamemode=0
> max-players=20
> max-tick-time=60000
> spawn-monsters=true
> generate-structures=true
> view-distance=10
> motd=A Minecraft Server
> 
> 把1.3.4的配置复制(复制后修改了端口 同时关掉了1.3.4防止影响)到1.4.0版配合1.3.4的存档则报错
> 但是用1.4.0生成默认的server配置(修改了端口)则不会报错
> 不知道是哪一项出了问题

![image](https://user-images.githubusercontent.com/30747164/82727852-9c4c1400-9d1f-11ea-8567-aec6a39ef44b.png)
上为对比报告，粗略看了一下应该是use-native-transport=true这一条产生的问题。
