### ISSUE TITLE
[BUG]EXU消防斧无法合成

### ISSUE THREAD

**Issue by dong031001** [ET-Team/EnigTech2#445]
**描述BUG**

**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by crystal-1214** [comment]
保暖三附魔书无法合成
增加保暖三附魔书获取方式
主要充当收藏品,其次听说可以配合AA的祛魔透镜来获取双倍附魔，比如时运VI，保护XIII等
![TIM图片20200516104822](https://user-images.githubusercontent.com/65433227/82108693-d8510900-9762-11ea-9988-68ea7934c4f1.png)
![TIM图片20200516104850](https://user-images.githubusercontent.com/65433227/82108696-da1acc80-9762-11ea-833c-ae39e8a461e1.png)

64位操作系统，基于x64的处理器
运行内存 5500
Java版本 jre-8u231
整合包版本 1.4.0
