### ISSUE TITLE
[BUG]更替之星无法用于制作元素象征

### ISSUE THREAD

**Issue by dong031001** [ET-Team/EnigTech2#446]
**描述BUG**

**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by ChromaPIE** [comment]
若“拿在手中右键”的方法可行，则附加tooltip于更替之星，请测试

**Comment by dong031001** [comment]
> 若“拿在手中右键”的方法可行，则附加tooltip于更替之星，请测试

驳回。这种方式只能作为权宜之计，并不直观。更倾向于写一个工作台配方来合成元素象征。
