### ISSUE TITLE
[BUG]1.4.0版本无法按F9显示区块边界和按F7显示刷怪区域

### ISSUE THREAD

**Issue by howardzhg** [ET-Team/EnigTech2#447]
**描述BUG**
1.4.0版本（未使用DLC）无法按F9显示区块边界和按F7显示刷怪区域，是否修改了JEI的快捷键，或者是键位冲突？另注，F3+G能够正常显示区块边界。

**如何重现**
使用MultiMC 5 启动器，版本0.6.11-1430，下载发布页EnigTech2-1.4.0.zip文件，将下载后的文件拖入启动器，点击OK，等下载好后，将内存设置为10240MB，点击运行，加载完毕后新建存档，打开作弊模式，打开奖励箱，其余默认，进入游戏，按F7和F9无反应。

**原本期望**
按F7显示刷怪区域，按F9显示区块边界

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：WIN10家庭版，版本1909（OS内部版本18363.836）
 - 运行内存：10240MB
 - Java版本：JAVA 8
- 整合包版本*：1.4.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
请自行添加MORE OVERLAY

**Comment by howardzhg** [comment]
好的，谢谢
