### ISSUE TITLE
[BUG]流体火箭发动机的配方问题

### ISSUE THREAD

**Issue by kater-kcl** [ET-Team/EnigTech2#451]
**描述BUG**
流体火箭发动机同时存在两个配方（原版和高级合成）
**如何重现**
**
**原本期望**
若无此BUG，原本你期待发生什么？
应删除原有配方
**截图**
暂无
**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：6G
 - Java版本：
- 整合包版本*：1.4.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by kater-kcl** [comment]
*应删除

**Comment by dong031001** [comment]
咱就不能编辑一下issue吗...

**Comment by kater-kcl** [comment]
> 咱就不能编辑一下issue吗...

不，就不（哼）
