### ISSUE TITLE
Cuisine模组的木手臂无合成

### ISSUE THREAD

**Issue by JellyGoat** [ET-Team/EnigTech2#452]
**描述建议**  
RT

**如何重现**  
........合成一下？

**原本期望**    
自动化.jpg

**截图**  
![Where is the wooden arm](https://s1.ax1x.com/2020/05/20/YoN21s.png)

**运行环境（请越详细越好）:**  
 - 操作系统*：Win10 Home x86_64  
 - 运行内存：8G（分配5G）  
 - Java版本： 如下  
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```
- 整合包版本*：EnigTech2-1.4.0  

**错误报告**   
非崩溃

**Comment by ChromaPIE** [comment]
**无法重现。**普通及专家模式均有合成。
