### ISSUE TITLE
[BUG]1.40版本，添加DLC4后新建存档后无法进入

### ISSUE THREAD

**Issue by zimei134** [ET-Team/EnigTech2#457]
**描述BUG**
1.40版本，添加DLC4后新建存档后无法进入，显示扫描器mod Scannable 出现问题。
**如何重现**

**原本期望**
正常运行1.40 DLC4 版本 

**截图**
![奔溃截图](https://user-images.githubusercontent.com/65797766/82720103-00041c00-9ce3-11ea-9edf-f625a6506984.png)

正常运行1.40 DLC4 版本 
**运行环境（请越详细越好）:**
 - 操作系统*：windows 10，x64
 - 运行内存：8g
 - Java版本：1.8.0_251
- 整合包版本*：1.40 DLC4 

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-05-23_10.47.09-client.txt](https://github.com/ET-Team/EnigTech2/files/4671033/crash-2020-05-23_10.47.09-client.txt)

**Comment by dong031001** [comment]
关闭光影/删除Optifine后重试

**Comment by zimei134** [comment]
已解决，非常感谢！
