### ISSUE TITLE
[BUG]新添加的附魔《即时存入》工作不完全正常

### ISSUE THREAD

**Issue by hashashin14** [ET-Team/EnigTech2#459]
**描述BUG**
1. 该附魔存在时《灼热》附魔不能起效
2. 该附魔存在时挖掘煤炭和钻石时《时运》附魔似乎未起效
3. 该附魔存在时并非所有的掉落物都会被取回
**如何重现**
1. 在已存在《即时存入》的一把增强宝石镐上附魔《灼热》并挖掘铁矿石，发现依然收到铁矿石而不是铁锭
2. 还是1那把镐子，之后附魔了《时运Ⅲ》，在挖掘煤炭和钻石的过程中至少连续10个以上矿石都各只掉落了1各煤炭或钻石，因为附近没有石英和红石故未测试其他情况，但推测应该是同样的情况
3. 在挖掘蓝宝石矿脉中的矿石的时候发现偶尔会发生宝石直接掉落而未收入背包中的情况（极其偶发，不清楚具体触发条件，可排除背包放满的情况），在用存在该附魔的弓射击烈焰人时发现只有烈焰棒被收入，掉落的固态经验、硫磺等其他掉落物均未被收入背包中而是掉落于生物被击杀位置
**原本期望**
1. 多个影响掉落规则的附魔与该附魔共存时能同时起效，或添加该附魔与其他影响掉落规则的附魔的冲突
2. 在击杀生物、采掘方块时正常收入所有的掉落物而不是收入一部分掉落一部分
**截图**
（无）
**运行环境（请越详细越好）:**
 - 操作系统*：WIN10 64位家庭中文版 1909 Build18363.836
 - 运行内存：16G
 - Java版本：1.8.0_251
- 整合包版本*：1.4.0

**错误报告**
（无）

**Comment by dong031001** [comment]
此附魔已经在#450 禁用，下个版本更新会附带。
