### ISSUE TITLE
[BUG]服务端问题

### ISSUE THREAD

**Issue by Yunth233** [ET-Team/EnigTech2#467]
连接服务器时出现如下文本:
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:snow_layer (RecipeStage{tier='two', recipe=6xtile.snow@0:[net.minecraft.item.crafting.Ingredient@e2b50840, net.minecraft.item.crafting.Ingredient@e2b50840, net.minecraft.item.crafting.Ingredient@e2b50840]}) produces unregistered item minecraft:snow_layer (net.minecraft.item.ItemSnow@80672a82)

版本:EnigTech2-1.4.1

![问题](https://user-images.githubusercontent.com/58768174/82905417-77ada180-9f96-11ea-97a2-1e4b5bb19438.png)

**Comment by 1870332922** [comment]
我之前也遇见过这个问题，请尝试重新安装客户端

**Comment by dong031001** [comment]
先前提供的服务端存在部分问题，请等待修复。

**Comment by Yunth233** [comment]
好的，加油

**Comment by dong031001** [comment]
已经重新上传

**Comment by Yunth233** [comment]
没问题了，谢谢
