### ISSUE TITLE
[待办]潘马斯

### ISSUE THREAD

**Issue by sun-wilhelm** [ET-Team/EnigTech2#475]
将潘马斯附属的物品加入Stage: one
这将包括：
+种子
+植物收获物
+树苗
+水果
+蔬菜
+蛛网 以及 纸 也应包括在树苗收获物中

除此之外，属于乡村模组的：
+栽培木桩
+葡萄
+辣椒
+番茄

也应该加入Stage: one

**Comment by dong031001** [comment]
无意义
