### ISSUE TITLE
[BUG]Extra cells ME气体发信器造成客户端崩溃

### ISSUE THREAD

**Issue by JoeyTesla12138** [ET-Team/EnigTech2#491]
**描述BUG**
用ME气体发信器控制自动合成气体的产量，使其保持在一个固定数值，方便参与自动合成。当标记所需气体时（mek基础气体储罐）客户端即发生退出服务器，退回服务器选择界面。
**如何重现**
标记ME气体发信器即可重现
**原本期望**
自动控制气体产量，优化自动化

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：WIN10
 - 运行内存：服务端6G，客户端4G
 - Java版本：241
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
可否上传服务端的log文件夹并给出崩溃的时间节点？

**Comment by JoeyTesla12138** [comment]
重新自查了问题，更换java251版本，重新解压安装包载入存档，但气体发信器无法标记任何气体（使用MEK气体储罐），shift+左键试图标记气体发生客户端崩溃，服务端未崩溃,附上客户端崩溃报告，经7次测试，崩溃概率100%
![image](https://user-images.githubusercontent.com/67106285/85128512-0515a600-b264-11ea-876d-9a73ad9940bb.png)
[crash-2020-06-19_19.32.35-client.txt](https://github.com/ET-Team/EnigTech2/files/4804361/crash-2020-06-19_19.32.35-client.txt)

**Comment by dong031001** [comment]
初步判断不是整合包问题，你可以向模组原Repo抛Issue。也许新版本更新模组版本也能够解决。
