### ISSUE TITLE
[BUG]流体储罐用流体漏斗导出蒸汽时崩溃，存档差点报废。

### ISSUE THREAD

**Issue by KevinLL218** [ET-Team/EnigTech2#499]
**描述BUG** 

**如何重现**
将装有蒸汽的流体储罐底部导出到流体漏斗中，且流体漏斗下面无实体方块（即导出到世界中），游戏会崩溃而且再次进入存档还是崩溃，不知道其他的流体会不会发生类似的状况。
可以通过修改流体漏斗mod的cfg文件关闭将流体导出到世界即可恢复。
若无此BUG，原本你期待发生什么？
建议蒸汽或其他某些流体进入流体漏斗时相当于流体垃圾桶，将其销毁。这样原有的功能不受影响，

**运行环境（请越详细越好）:**
 - 操作系统*：Win10
 - 运行内存：10240mb
 - Java版本：1.8
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-06-26_15.18.29-client.txt](https://github.com/ET-Team/EnigTech2/files/4839639/crash-2020-06-26_15.18.29-client.txt)

**Comment by UOYZAL** [comment]
蒸汽是气体，建议发明气体漏斗

**Comment by KevinLL218** [comment]
> 蒸汽是气体，建议发明气体漏斗
主要是当时把方镁矾和蒸汽弄混了都是差不多颜色，放上去莫名其妙就崩溃了。另外，蒸 氵气是气液共存态，蒸气才是气态，液体漏斗没毛病，当然你也可以发明蒸汽漏斗，不过打麻将不建议吃碰。不然不容易8番了
