### ISSUE TITLE
[BUG]搬运过程中机械丢失

### ISSUE THREAD

**Issue by sun-wilhelm** [ET-Team/EnigTech2#501]
**描述BUG**
在服务器里搬家的时候搬运氯化机等机械，结果导致其丢失。

**如何重现**
使用玻璃镐挖掘机器。

_PS：有一个人私聊找我反馈的，我暂时没验证。他不会发issue，我来替他发一个。_

**Comment by dong031001** [comment]
EXU2 BUG，无法修复。
