### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Young080718** [ET-Team/EnigTech2#502]
**描述BUG**
在(不小心)加入ExtraBotany(版本r1.1-58r)时,模组etutil发生崩溃，且无法再次启动
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
我要启动游戏啊!!!!!!!!!!!!!!!!
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Win10
 - 运行内存：16GB
 - Java版本：不清楚
- 整合包版本*：1.4.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-07-02_17.03.11-client.txt](https://github.com/ET-Team/EnigTech2/files/4863204/crash-2020-07-02_17.03.11-client.txt)

**Comment by dong031001** [comment]
请移除ExtraBotany模组。
