### ISSUE TITLE
[BUG]主线星辉合成台无法合成辉光粉和暗夜粉

### ISSUE THREAD

**Issue by LinKin-tech** [ET-Team/EnigTech2#517]
**描述BUG**
主线任务星辉合成台无法合成辉光粉和暗夜粉
**如何重现**
星能满也无法合成
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：16G
 - Java版本：1.8
- 整合包版本*：v1.4.1-Release

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
仔细阅读相关进度描述
如仍然迷惑，查阅[http://129.211.167.41/index.php/%E6%95%99%E7%A8%8B/ET2%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%90%88%E9%9B%86#.E4.B8.BA.E4.BB.80.E4.B9.88.E6.88.91.E7.9A.84.E5.85.B1.E9.B8.A3.E4.B9.8B.E6.9D.96.E4.B8.8D.E8.83.BD.E5.90.88.E6.88.90.E8.BE.89.E5.85.89.E7.B2.89.EF.BC.9F](ETwiki相关Q&A)
