### ISSUE TITLE
[BUG] 硅生长器 无法通过流体管道向内部输送流体。

### ISSUE THREAD

**Issue by 284354572** [ET-Team/EnigTech2#519]
**描述BUG**
EXU2机器 硅生长器 无法通过某些流体管道向内部输送流体，包括但不限于 Flopper流体漏斗 EIO液体导管 TD流体管道 Embers流体管道 EIO流体储罐。本人测试仅 TE便携储罐 可向内输入流体。
**如何重现**
尝试使用流体导管向 硅生长器 内输入流体。
**原本期望**
若无此BUG，原本你期待发生什么？
硅生长器 可通过流体管道向内部输送流体。
**截图**
![1](https://user-images.githubusercontent.com/47343409/88314437-8078e480-cd47-11ea-9285-53f007df3ba2.png)
**运行环境（请越详细越好）:**
 - 操作系统*：Win10 专业版 2004
 - 运行内存：8.00 GB
 - Java版本：build 1.8.0_261-b12
- 整合包版本*：v1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by 284354572** [comment]
若输入星能液，则TD管道可以，其余依然不行。
[![UfMdSJ.th.png](https://s1.ax1x.com/2020/07/20/UfMdSJ.th.png)](https://imgchr.com/i/UfMdSJ)

**Comment by UOYZAL** [comment]
很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug

另外，问题解决后，请自行Close Issue

**Comment by 284354572** [comment]
> 很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug
> 
> 另外，问题解决后，请自行Close Issue

exu自带机器均无此bug，只有自定义机器有

**Comment by UOYZAL** [comment]
> > 很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug
> > 
> > 另外，问题解决后，请自行Close Issue
> 
> exu自带机器均无此bug，只有自定义机器有

和我说的并不冲突

**Comment by 284354572** [comment]
> > > 很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug
> > > 另外，问题解决后，请自行Close Issue
> > 
> > 
> > exu自带机器均无此bug，只有自定义机器有
> 
> 和我说的并不冲突

若果是exu的兼容问题的话，他本来就有的机器通过其他第三方管道输入应该也会有问题，但现在只有自定义的机器有问题，说明是自定义机器写的有问题，也就是整合包设计这个机器的时候有问题，故和你说的有冲突

**Comment by UOYZAL** [comment]
> > > > 很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug
> > > > 另外，问题解决后，请自行Close Issue
> > > 
> > > 
> > > exu自带机器均无此bug，只有自定义机器有
> > 
> > 和我说的并不冲突
> 
> 若果是exu的兼容问题的话，他本来就有的机器通过其他第三方管道输入应该也会有问题，但现在只有自定义的机器有问题，说明是自定义机器写的有问题，也就是整合包设计这个机器的时候有问题，故和你说的有冲突

兄啊，翻翻代码，我说的是exu2对自定义机器的兼容问题

**Comment by dong031001** [comment]
> > > > 很明显，这是一个ExtraUtilities2 mod的兼容问题，并不是整合包bug
> > > > 另外，问题解决后，请自行Close Issue
> > > 
> > > 
> > > exu自带机器均无此bug，只有自定义机器有
> > 
> > 
> > 和我说的并不冲突
> 
> 若果是exu的兼容问题的话，他本来就有的机器通过其他第三方管道输入应该也会有问题，但现在只有自定义的机器有问题，说明是自定义机器写的有问题，也就是整合包设计这个机器的时候有问题，故和你说的有冲突

**是模组提供设计机器的接口有问题**
