### ISSUE TITLE
根源魔法书打开特定篇章会导致崩溃

### ISSUE THREAD

**Issue by flag-go** [ET-Team/EnigTech2#521]
[crash-2020-07-25_01.30.21-client.txt](https://github.com/ET-Team/EnigTech2/files/4973572/crash-2020-07-25_01.30.21-client.txt)

**Comment by flag-go** [comment]
版本1.4.1

**Comment by UOYZAL** [comment]
这是一个mod bug，请参见https://github.com/MysticMods/Roots/issues/171 获取帮助

注：下次发送issue时，**请**使用issues模板
