### ISSUE TITLE
[求助]多人游戏服务器配置的一些问题

### ISSUE THREAD

**Issue by jerrita** [ET-Team/EnigTech2#525]
大大您好，这里有些问题想要求助。
为了和小伙伴一起玩耍，我把服务端换成了catserver，并把服务包解压到了对应文件夹中
![1](https://user-images.githubusercontent.com/28153001/88476684-088c0380-cf6d-11ea-896c-7efc13757301.png)
但在开服过程中出现了几个问题
![2](https://user-images.githubusercontent.com/28153001/88476761-9a940c00-cf6d-11ea-8237-8abc75b633ed.png)
直接开服fastbench会导致崩溃，删掉后可正常运行，不知道会不会出事
![3](https://user-images.githubusercontent.com/28153001/88476727-56a10700-cf6d-11ea-9af5-ef59337ed1b2.png)
若不提前设置op，玩家进入时会出现如图所示的情况，不知道应该如何解决呢？
谢谢！

**Comment by dong031001** [comment]
ET2对猫端支持不佳，不推荐使用猫端作为服务端。

**Comment by jerrita** [comment]
> ET2对猫端支持不佳，不推荐使用猫端作为服务端。

那有没有推荐的服务端呢，主要是想加入一个多世界的插件，人多的话怕资源不够

**Comment by dong031001** [comment]
> > ET2对猫端支持不佳，不推荐使用猫端作为服务端。
> 
> 那有没有推荐的服务端呢，主要是想加入一个多世界的插件，人多的话怕资源不够

之前有所耳闻墨端可以支持ET2，本人没有尝试过就是了。多世界的话建议使用/rtp指令，可以在十万格半径内随机传送，不会有资源问题。

**Comment by jerrita** [comment]
> > > ET2对猫端支持不佳，不推荐使用猫端作为服务端。
> > 
> > 
> > 那有没有推荐的服务端呢，主要是想加入一个多世界的插件，人多的话怕资源不够
> 
> 之前有所耳闻墨端可以支持ET2，本人没有尝试过就是了。多世界的话建议使用/rtp指令，可以在十万格半径内随机传送，不会有资源问题。

嗯嗯好，我去试试，谢谢了^_^

**Comment by UOYZAL** [comment]
有关FastWorkBench问题，见https://github.com/Luohuayu/CatServer/issues/30

**Comment by jerrita** [comment]
> 之前有所耳闻墨端可以支持ET2，本人没有尝试过就是了。多世界的话建议使用/rtp指令，可以在十万格半径内随机传送，不会有资源问题。

试了一下rtp，会直接导致水分归零，不清楚是特性还是就是那么设计的，有修改的方式吗？

**Comment by UOYZAL** [comment]
> > 之前有所耳闻墨端可以支持ET2，本人没有尝试过就是了。多世界的话建议使用/rtp指令，可以在十万格半径内随机传送，不会有资源问题。
> 
> 试了一下rtp，会直接导致水分归零，不清楚是特性还是就是那么设计的，有修改的方式吗？

并不是清零，是一次性扣很多
跑太久水分就会掉的设计造成的特性，其实你传送了那么远扣你些水分挺合理的
