### ISSUE TITLE
[BUG]血魔法的路由网络不能同时用多个输出节点来输出液体

### ISSUE THREAD

**Issue by FFFeiXXX** [ET-Team/EnigTech2#532]
**描述BUG**
血魔法的路由网络不能同时用多个输出节点来输出液体。不过可以同时输出物品。

**如何重现**
一个路由网络，一个输入节点输入液体（如水），先用一个输出节点输出，等输出满连接的容器，再连接上第二个输出节点，然后就会发现第二个输出节点无法输出到外面的容器。

**原本期望**
若无此BUG，原本你期待发生什么？
同种液体在世界各处方便装取，如世界各处的无限水（只需一个容器和一个输出节点）

**截图**
![2020-08-13_22 50 29](https://user-images.githubusercontent.com/67513571/90150009-bbef5780-ddb7-11ea-96cb-e33208a5492b.png)

**运行环境（请越详细越好）:**
 - 操作系统*：windows10 LTSC 1809 17763.1282
 - 运行内存：16gb（分配mc 12gb）
 - Java版本：工作版本 1.8.0_251-b08
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
这并不是整合包bug，请移步对应mod的repo
