### ISSUE TITLE
[BUG]打开Roots模组的指南书The Druidic Arts(#8058)存档崩溃

### ISSUE THREAD

**Issue by ChillsLove** [ET-Team/EnigTech2#535]
**描述BUG**
打开Roots模组的指南书The Druidic Arts(#8058)存档崩溃
**如何重现**
打开Roots模组的指南书The Druidic Arts(#8058)存档崩溃，打开指南书内的任意篇章崩溃
**原本期望**
若无此BUG，原本你期待发生什么？
我想使用指南书查询仪式效果
**截图**
![20200816203639](https://user-images.githubusercontent.com/38351612/90334448-4c1fdd80-e000-11ea-9279-a5c0b14bad71.png)

**运行环境（请越详细越好）:**
 - 操作系统*：64位
 - 运行内存：8G
 - Java版本：Java8
- 整合包版本*：EnigTech2-v1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-08-16_19.12.36-client.txt](https://github.com/ET-Team/EnigTech2/files/5080639/crash-2020-08-16_19.12.36-client.txt)
[crash-2020-08-16_20.29.34-client.txt](https://github.com/ET-Team/EnigTech2/files/5080640/crash-2020-08-16_20.29.34-client.txt)
[crash-2020-08-16_19.00.15-client.txt](https://github.com/ET-Team/EnigTech2/files/5080641/crash-2020-08-16_19.00.15-client.txt)

**Comment by UOYZAL** [comment]
与 #521 重复
经过查证，根源魔法书打开崩溃的原因是汉化资源包的一个问题，属于非整合包范畴，不予受理
