### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by m2462348456** [ET-Team/EnigTech2#536]
ender io护甲 玄钢物品栏刷物品 玄钢物品栏升级 打开物品栏装满东西右键物品展示框
**原本期望**
 打开箱子不小心把旅行权杖上到物品展示框然后发现复制了东西
**截图**
![R$_M8L_%8CS5MCG(2Q_~6`9](https://user-images.githubusercontent.com/69783514/90361402-b1231400-e090-11ea-9ef2-de32f52927f9.png)
![(SM53`Q }K4 9V$J%B%Y @3](https://user-images.githubusercontent.com/69783514/90361396-ae282380-e090-11ea-9e3e-7c9b6945ff6c.png)
![R$_M8L_%8CS5MCG(2Q_~6`9](https://user-images.githubusercontent.com/69783514/90361397-aec0ba00-e090-11ea-8181-9b58a48d9d11.png)

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：8024
 - Java版本：java8
- 整合包版本*：1.5.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
玄钢升级刷物品老bug了，不是整合包问题
