### ISSUE TITLE
[BUG]游戏的方块粒子消失

### ISSUE THREAD

**Issue by ChillsLove** [ET-Team/EnigTech2#540]
**描述BUG**
我一次打开游戏后，游戏的方块粒子消失了，例如：挖方块的方块破碎粒子，植物魔法白雏菊周围方块的白色光效，火红莲的燃烧粒子都没有了。
**如何重现**
未知
**原本期望**
若无此BUG，原本你期待发生什么？
无
**截图**
![Badlion Client 2020 08 20 - 22 37 50 04_x264 00_00_00-00_00_30](https://user-images.githubusercontent.com/38351612/90786842-a8536c00-e336-11ea-92ba-619c6d160cf2.gif)

**运行环境（请越详细越好）:**
 - 操作系统*：64位
 - 运行内存：8G
 - Java版本：java8
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
未崩溃

**Comment by UOYZAL** [comment]
:)
