### ISSUE TITLE
[BUG]进度中换行符未转义

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#542]
**描述BUG**
进度中换行符未转义，仍然是\n。
**如何重现**
查看进度即可
**原本期望**
若无此BUG，原本你期待发生什么？
正常换行
**截图**
![1](https://user-images.githubusercontent.com/11871061/91006639-7ed36280-e60c-11ea-9c12-3ca70cf97233.png)
![批注 2020-08-24 131408](https://user-images.githubusercontent.com/11871061/91006642-7f6bf900-e60c-11ea-81c1-9daa089291e1.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
此bug已在预览版中修复
