### ISSUE TITLE
[BUG]创建存档或初次进入时会给予车万女仆书

### ISSUE THREAD

**Issue by sjdhome** [ET-Team/EnigTech2#543]
**描述BUG**
如题，而这应该在阶段维塔享受生活中才应该自行触发，否则在游戏开始时就透露了部分内容。
**如何重现**
创建新存档
**原本期望**
若无此BUG，原本你期待发生什么？
不会自动得到书
**截图**
![批注 2020-08-24 132305](https://user-images.githubusercontent.com/11871061/91006804-f6a18d00-e60c-11ea-92c7-4776fb40180a.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.4.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
此bug已在预览版中修复
