### ISSUE TITLE
[BUG]压挤印记BUG（不确定是mod问题还是整合包问题）

### ISSUE THREAD

**Issue by zjq695565800** [ET-Team/EnigTech2#548]
**描述BUG**
压挤印记不知道为什么会修改掉原版矿物合成表，将9个锭合成一个块修改为9个锭合成为64个块。

**如何重现**
挖矿（在磷矿脉里，青金石问题尤为突出），带着激活的压挤印记。当背包临近满的时候大量挖矿，保证包里有部分青金石，背包爆满，地上还有满地的青金石的时候，然后按下R键整理，大概率就会把青金石锭变块的合成表修改掉，但是重开游戏后会恢复正常。

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![QQ截图20200902112748](https://user-images.githubusercontent.com/60031595/91932837-db064880-ecd6-11ea-833b-ab16206c54fd.png)
![QQ截图20200902112805](https://user-images.githubusercontent.com/60031595/91932839-de013900-ecd6-11ea-9460-cf1b34a2cd4e.png)
![QQ截图20200902112942](https://user-images.githubusercontent.com/60031595/91932841-de013900-ecd6-11ea-91a8-0cf21b7bf672.png)
![QQ截图20200902112950](https://user-images.githubusercontent.com/60031595/91932842-df326600-ecd6-11ea-8af5-8fa1106fda2c.png)

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by UOYZAL** [comment]
血魔法bug，无法修复
