### ISSUE TITLE
[BUG]1.5.0版本高强合金合成表丢失

### ISSUE THREAD

**Issue by lc1lc2lc3** [ET-Team/EnigTech2#552]
**描述BUG**
1.5.0版本高强合金合成表丢失

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：12000
 - Java版本：1.8.0（64bit）
- 整合包版本*：1.5.0

**Comment by dong031001** [comment]
问题在重启游戏后持续出现吗

**Comment by lc1lc2lc3** [comment]
重启后正常了
