### ISSUE TITLE
[其他]License的问题

### ISSUE THREAD

**Issue by takayama-lily** [ET-Team/EnigTech2#553]
CC本身并不适合开源协议。
如果非要用的话，要允许别人 **fork-修改-pr** 应该使用宽松一步的 `CC BY-NC-SA` 而非 `CC BY-NC-ND`
fork后修改已经可以被视为违反`CC BY-NC-ND`的行为了。

**Comment by UOYZAL** [comment]
连团队人员对repo进行修改都要交pr，大概没什么换协议的必要，望周知

**Comment by dong031001** [comment]
感谢反馈。在项目接近尾声的现在，许可的确可以考虑更换为更宽松的开源协议。

**Comment by dong031001** [comment]
> 连团队人员对repo进行修改都要交pr，大概没什么换协议的必要，望周知

1.团队人员对Repo的修改不受限制，只是Repo开启了Master Branch的保护而已。
2.开启Branch保护并使用MIT等宽松协议的Repo在GitHub上可谓茫茫多，望周知。
