### ISSUE TITLE
[BUG]根源魔法 守门者法杖 花仙盾咒术 无消耗 无冷却 过于无敌

### ISSUE THREAD

**Issue by 1666325182** [ET-Team/EnigTech2#557]
**描述BUG**
只要在药草口袋里放上1个灵魂草即可无限使用花仙盾咒术，无消耗，无冷却，过于无敌（花瓣可以免疫攻击伤害），建议修改一波
**如何重现**
如上，药草口袋灵魂草，手持注入了花仙盾咒术的守门者法杖鼠标右击即可重现
**原本期望**
若无此BUG，原本你期待发生什么？
原版模组应该是使用一次添加一枚花瓣再加消耗和冷却，bug后使用一次加3个花瓣无消耗无冷却，加3个花瓣我倒觉得ok，可是无消耗无冷却也太无敌了
**截图**
无，实际用一下应该就行
**运行环境（请越详细越好）:**
 - 操作系统*：win10家庭版64位
 - 运行内存：16G
 - Java版本：8
- 整合包版本*：1.5.0+我自己开的服务端和基友一起玩

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
无

**Comment by dong031001** [comment]
模组BUG，无能为力。
