### ISSUE TITLE
[BUG]無法合成耕地

### ISSUE THREAD

**Issue by Dep0s1t** [ET-Team/EnigTech2#558]
**描述BUG**
無法合成耕地
**如何重现**
![20201206_001314](https://user-images.githubusercontent.com/52196755/101249684-505f3a80-3758-11eb-936a-ff423a18a99f.jpg)

**原本期望**
若无此BUG，原本你期待发生什么？
合成出耕地
**截图**
![20201206_001314](https://user-images.githubusercontent.com/52196755/101250244-797fcb00-3758-11eb-9cb9-c98c30763fc4.jpg)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10
 - 运行内存：16G
 - Java版本：1.8.0_271
- 整合包版本*：1.5.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by Dep0s1t** [comment]
火把也没法合成，都是按照jei显示的来做的。

**Comment by dong031001** [comment]
请确保服务端跟客户端版本及模式一致
