### ISSUE TITLE
床[BUG]

### ISSUE THREAD

**Issue by 198agk** [ET-Team/EnigTech2#570]
![d6681a531aa26904538555ebef068ab](https://user-images.githubusercontent.com/76952257/103538180-b7474f00-4ed0-11eb-8a11-6c0b347ffe36.png)
在睡觉的时候，输入文字并发出时，或即将起床时发出文字和打文字，起床后就会卡在这页面然后什么也做不了了，只能关闭游戏重新开启

**Comment by 198agk** [comment]
整合包1.5.2

**Comment by dong031001** [comment]
未能重现
