### ISSUE TITLE
[其他]关于修复增加配方的建议

### ISSUE THREAD

**Issue by WaterFoxR** [ET-Team/EnigTech2#575]
1、普通模式下的集成装配机MK1制作魔能马达产量已于最近版本从1修复成2，但其升级版MK2的配方仍为1＋1（10%额外产出），应为2＋1（10%）。
2、普通模式下原子阶段的组合合成配方仅有各水晶增生之种配方，建议继承AA充能台所有配方

**Comment by dong031001** [comment]
暂无计划实现2.
