### ISSUE TITLE
[BUG]1.5.3专家版无法合成Vibrant Jetpack

### ISSUE THREAD

**Issue by Karma-Tress** [ET-Team/EnigTech2#577]
**描述BUG**
如题，因怀疑过是电容的问题曾尝试充满电/改变电容输出模式，未果。服务端和客户端均为专家模式。
**如何重现**
解锁游戏阶段五并试图合成Vibrant Jetpack
**原本期望**
若无此BUG，原本你期待发生什么？
正常游戏
**截图**
以下为单人测试
![$Y T4TCL@$LO ~K0OQD)@Z9](https://user-images.githubusercontent.com/78328385/106404187-f4214a00-646c-11eb-909b-611ef68243a5.png)
![SWPSPF(G`BQ3DC DNI%I)LP](https://user-images.githubusercontent.com/78328385/106404226-1adf8080-646d-11eb-9bc4-405f06e555ac.png)
以下为服务器测试
![K(}_2D8 I( K FT3D_}D~`G](https://user-images.githubusercontent.com/78328385/106404296-55e1b400-646d-11eb-9231-1dfcbbca7d0f.png)
![EP%F2)_2QV)15Q}F$~0NR97](https://user-images.githubusercontent.com/78328385/106404337-714cbf00-646d-11eb-9820-3f456f2fead6.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10 20H2
 - 运行内存：8g
 - Java版本：jre1.8.0_181
- 整合包版本*：1.5.3

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by Karma-Tress** [comment]
![Uploading CEAMV(INGHQA6FIU6`$J`J6.png…]()

**Comment by dong031001** [comment]
能不能看看最新版本是什么
