### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by youngxs12138** [ET-Team/EnigTech2#579]
**描述BUG**
背包与墓碑冲突
**如何重现**
随机触发，打开自己的墓碑后背包会消失，第二个背包有概率会被第一个背包顶掉（第二个消失，第一个出现在身上）
**原本期望**
若无此BUG，原本你期待发生什么？
返还我的背包
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：16G
 - Java版本：1.8.7
- 整合包版本*：V1.5.4

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
看看自己的饰品栏
