### ISSUE TITLE
[BUG]关于信标无法在正常距离内作用的BUG

### ISSUE THREAD

**Issue by SeemsDawn** [ET-Team/EnigTech2#580]
**描述BUG**
在游戏正常游玩的情况下制作信标，结果发现信标只有在信标方块周围有方块更新的时候会给予玩家一次buff。
有时候距离信标非常近或者范围边缘的时候才能获得buff。尝试了在领地外或者领地内都会有这个bug

**如何重现**
正常制造一个信标

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：服务器和客户端均为x86平台，分别是Centos7和Win10
- 整合包版本*：ET2-1.5.4
- Java版本:1.8.0_265[服务器]，内存分配Max 6G[服务器]

**Comment by dong031001** [comment]
1.12.2原版的BUG，建议用高频红石保持激活（bushi

**Comment by SeemsDawn** [comment]
我在服务器中config中betterfps.json中把"fast Beacon":true,   快速信标给设置成false了。目前信标正常了，这貌似是betterfps与原版的冲突。
