### ISSUE TITLE
[BUG]原木合成木板配方空白

### ISSUE THREAD

**Issue by iMusynx** [ET-Team/EnigTech2#583]
**描述BUG**
如图

**如何重现**
JEI搜索木板合成表
**原本期望**
无序合成合成木板
若无此BUG，原本你期待发生什么？
可以合成木板
**截图**
![图片](https://user-images.githubusercontent.com/40123877/109813018-b0189500-7c24-11eb-9ab8-1806b82de958.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Win10 LTSC 2019
 - 运行内存：16G
 - Java版本：Java is version 1.8.0_252, using 64-bit architecture, from BellSoft.(OpenJDK8)
- 整合包版本*：1.5.4 Normal

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
配方显示错误，EIO Bug，原本就无法合成
