### ISSUE TITLE
[BUG] Bukkit 服务端墓碑处理玩家死亡不正确

### ISSUE THREAD

**Issue by JingBh** [ET-Team/EnigTech2#585]
由于我的服务器有使用插件的需求，整合包内置的 Forge 服务端无法满足，我尝试了 [CatServer](https://github.com/Luohuayu/CatServer) 和 [Mohist](https://github.com/Mohist-Community/Mohist) 两个服务端，但都遇到了玩家死亡时墓碑处理不正确的问题，具体表现为：

 - 重生后保留死亡前最大生命值
 - 重生后保留死亡前口渴值，若死亡前口渴值已耗尽，重生后显示为满，但实际还是空的，如果不及时喝水会再次被渴死
 - 死亡后不保留经验值

同时控制台警告如下：
```
[WARN] Player <name> just died and respawned in their old body. Did someone fire a PlayerEvent.Clone(death=true) for a teleportation? Supressing Soulbound enchantment for zombie player.
```

由于两个服务端都有这样的问题，但内置的 Forge 服务端没有问题，故猜测是只存在于 Bukkit 服务端的问题。

不清楚此问题是整合包导致的还是墓碑 mod 导致的，所以就发在这里了，还请大佬指点。

## 如何重现

1. 下载 EnigTech2 服务端整合包
2. [下载 Mohist 服务端](https://mohistmc.com/builds/1.12.2/mohist-1.12.2-199-server.jar)
3. 运行 Mohist 服务端
4. 客户端加入游戏，获取任意方块（使墓碑生成）并死亡
5. **点击复活**
6. 完成复现

**无需加载任何服务端插件即可复现，故认为不是插件引发的错误。**

## 原本期望

死亡后的处理与使用 Forge 服务端一致。

## 截图

截图无法体现此问题，可以参考上面的控制台信息。

## 运行环境（请越详细越好）:
 - 操作系统：服务器端未知，本地复现使用 Windows 10
 - 运行内存：为 Java 分配 4GB
 - Java版本：1.8.0_281
 - 整合包版本：1.5.6

## 错误报告

*游戏未崩溃*

**Comment by dong031001** [comment]
请将issue转至对应模组和服务端核心repo，这个问题超出了整合包作者能够解决的领域。

**Comment by JingBh** [comment]
只安装墓碑 mod 使用 Mohist 服务端并不会出现这个问题，可以认为这个问题并不出在 mod 本身，而是整合包中某（些）mod 不兼容导致的，所以我反馈在这，希望整合包作者能协助排查。

**Comment by dong031001** [comment]
> 只安装墓碑 mod 使用 Mohist 服务端并不会出现这个问题，可以认为这个问题并不出在 mod 本身，而是整合包中某（些）mod 不兼容导致的，所以我反馈在这，希望整合包作者能协助排查。

这个Repo只受理未经修改的客户端/服务端出现的问题。
