### ISSUE TITLE
[BUG]高级火箭 火箭卸载器无法使用

### ISSUE THREAD

**Issue by assassin-game** [ET-Team/EnigTech2#586]
**描述BUG**
高级火箭模组，连接器连接火箭卸载器时会识别成火箭装载器，导致采矿火箭无法卸载矿石。
**如何重现**
重复连接器连接火箭卸载器，依旧识别成火箭装载器。
**原本期望**
若无此BUG，原本你期待发生什么？
有此bug游戏无法进行下去，卡在钼矿石无法获取，无此bug就可以开心得继续往下玩耍。
**截图**
![2021-05-13_11 31 49](https://user-images.githubusercontent.com/84114219/118080738-14a65c00-b3ed-11eb-837c-260c11bc8b6b.png)

**运行环境（请越详细越好）:**
 - 操作系统*：64 位操作系统
 - 运行内存：16G(15.8G可用)
 - Java版本：1.8.0_291-b10
- 整合包版本*：1.5.4 expert

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
模组BUG，下个版本会更新模组版本应该可以修复这个问题。你直接把火箭解体然后从箱子里面取物品也可以获得到内容物。

**Comment by assassin-game** [comment]
刚才试了几次，然而箱子里并没有矿物,难过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ET-Team/EnigTech2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ET-Team/EnigTech2] [BUG]高级火箭 火箭卸载器无法使用 (#586)





 
模组BUG，下个版本会更新模组版本应该可以修复这个问题。你直接把火箭解体然后从箱子里面取物品也可以获得到内容物。

**Comment by dong031001** [comment]
那只能说明你挖矿过程有问题。

**Comment by assassin-game** [comment]
搞定了，原来是小行星ID芯片没有加3种数据，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ET-Team/EnigTech2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ET-Team/EnigTech2] [BUG]高级火箭 火箭卸载器无法使用 (#586)





 
那只能说明你挖矿过程有问题。
