### ISSUE TITLE
[BUG] v1.5.6服务器中无法合成耕地

### ISSUE THREAD

**Issue by c5cle** [ET-Team/EnigTech2#592]
**描述BUG**
无法合成耕地，无论是创造还是生存都不行
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
种地

**截图**
![image](https://user-images.githubusercontent.com/56671041/123418940-4580d000-d5ec-11eb-93a8-23bb19e0898f.png)

**运行环境（请越详细越好）:**
 - 操作系统*：linux
 - 运行内存：4G
 - Java版本：8
- 整合包版本*：1.5.7

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
确保服务端和客户端模式一致。
