### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nidhogg-Ale** [ET-Team/EnigTech2#593]
**描述BUG**
ET2 服务器
玩家使用AE2无线样板终端导致崩溃

**如何重现**
AE2模组用户未经过安全终端，使用无线样板终端导致服务器崩溃。
（并不确定是这样做造成的，仅根据当时服务器中受害玩家描述推测）

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Linux (amd64) version 3.10.0-957.el7
 - 运行内存：7.8Gb server
 - Java版本：1.8.0.282
- 整合包版本*：1.5.6server/1.5.7client

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2021-07-01_14.15.35-server.txt](https://github.com/ET-Team/EnigTech2/files/6746026/crash-2021-07-01_14.15.35-server.txt)

**Comment by dong031001** [comment]
模组BUG，请报告至https://github.com/p455w0rd/WirelessPatternTerminal
