### ISSUE TITLE
[BUG]无法种植甜菜根

### ISSUE THREAD

**Issue by SRARS** [ET-Team/EnigTech2#599]
**描述BUG**
我的存档，种下去的甜菜不生长，用骨粉也无法催熟，创建新的存档也无法生长和催熟。当我把我的存档删除，再创新档，甜菜根也无法生长和催熟。
当重新安装客户端后，可以生长和催熟。一但再次加载我的存档，就又无法生长和催熟，创新新的存档也无法无法生长和催熟。
其他作物都能正常生长。
**如何重现**
未知
**原本期望**
种植甜菜合成物品，无法获得甜菜根导致我无法继续进行游戏，解锁下一阶段

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 家庭中文版20H2 19042.1083
 - 运行内存：16G
 - Java版本：1.8.0_291
- 整合包版本*：1.5.7
[新的世界.zip](https://github.com/ET-Team/EnigTech2/files/6797292/default.zip)

**Comment by dong031001** [comment]
仔细阅读进度
