### ISSUE TITLE
未知情况导致服务器崩溃

### ISSUE THREAD

**Issue by nvvv4900** [ET-Team/EnigTech2#604]
**描述BUG**
未知情况导致服务器崩溃
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![Uploading E7F2A73FE220CA4ACCF1A6F54FD38A54.png…]()
**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：4g
 - Java版本：最新
- 整合包版本*：最新

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2021-08-11_12.09.53-server.txt](https://github.com/ET-Team/EnigTech2/files/6965982/crash-2021-08-11_12.09.53-server.txt)

**Comment by dong031001** [comment]
服务器卡崩了
