### ISSUE TITLE
[BUG]EXU2的消音器错误

### ISSUE THREAD

**Issue by liunian666chenxi** [ET-Team/EnigTech2#611]
**描述BUG**
进存档就崩了
**如何重现**
再次进存档
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win 11
 - 运行内存：3.5G
 - Java版本：8
- 整合包版本*：1.5.7

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2021-12-16_17.29.52-server.txt](https://github.com/ET-Team/EnigTech2/files/7768184/crash-2021-12-16_17.29.52-server.txt)

**Comment by dong031001** [comment]
根据报告来看是因为exu2的消音器消音AE2的某个方块导致的。
方块坐标在 (-306,91,240)
你可以尝试回档或者删除这个坐标所在区块来解决。
