### ISSUE TITLE
[BUG]骨粉有部分作物，野木树苗，神秘花瓣无法催熟

### ISSUE THREAD

**Issue by yourlit** [ET-Team/EnigTech2#612]
**描述BUG**
如题
**如何重现**
可以录视频，发存档
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
一阶段所有进度读完

**Comment by yourlit** [comment]
> 一期所有最后读完

我已经完成了，二阶段都到魔力符文了，之前都是可以用的，突然就不行了

**Comment by dong031001** [comment]
那你没看见有一个叫温室玻璃的进度？
