### ISSUE TITLE
[BUG]提供修复根源魔法指导书打开崩端、退地图缓慢方法

### ISSUE THREAD

**Issue by Fodoth-jinzi89** [ET-Team/EnigTech2#614]
**描述BUG**
#521 #535 
已经查明这是由于i18nupdate自动汉化更新模组引起的问题。由于现在的根源魔法已经更新到3.1版本，很多内容都有改动，i18nupdate也相应的更新到了3.1版本的翻译，然而玄理使用的是3.0版本，载入了3.1版本的根源魔法指导书汉化，导致崩溃。这是主要的问题。
我在游戏根目录的resources看到了3.0版本的根源魔法指导书翻译，不知道作者们是否做过修复尝试。这个翻译文采斐然，但是不全。在游戏中，i18nupdate的资源包是优先于resources中的翻译加载的。
模组本身也有一部分魔咒和物品没有汉化，在此提供自己制作的3.0版本指导书翻译和汉化补全：

[roots指导书翻译及汉化补全.zip](https://github.com/ET-Team/EnigTech2/files/8014496/roots.zip)

书本身也有一个小问题。元素土一章由于resources中的合成表禁用未生效，会出现一个页面错误。提供的文件已经修复了。
根源魔法指导书打开崩端的问题带来的附加效应是退出地图异常地缓慢。解决了以后，退出地图速度有一定提升。
**如何重现**
文件的具体整合交由你们完成。
**原本期望**
修复以后，模组全汉化正常加载，退地图速度有一定提升。
**截图**
![image](https://user-images.githubusercontent.com/49546344/152773089-44292976-b7f9-45cb-bd10-e632a30346cd.png)
![image](https://user-images.githubusercontent.com/49546344/152773123-dc66fc4c-5735-4329-b474-d26ec56e3e75.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10
 - 运行内存：8G
 - Java版本：IBM Semeru jdk-8.0.312.7-openj9
- 整合包版本*：1.5.7

**错误报告**
这个报告没有什么用处。如果需要，请见之前的issue

**Comment by dong031001** [comment]
你好，整合包已在1.6.0更新中更新Roots版本，感谢您的贡献。
