### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Josh112342** [ET-Team/EnigTech2#617]
整合包安装失败
Caused By: 下载 Mod失败
Caused By: 文件下载失败：E:\我的世界\.minecraft\versions\EnigTech 2 (玄理2)\mods\PackModeMenu-1.0.2.jar（第一下载源：https://media.forgecdn.net/files/3122/074/PackModeMenu-1.0.2.jar）
Caused By: 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException

**Comment by dong031001** [comment]
非整合包BUG
