### ISSUE TITLE
[BUG]1.5.6使用CatServer作为服务端时，服务器玩家无法默认解锁阶段1

### ISSUE THREAD

**Issue by djp440** [ET-Team/EnigTech2#619]
**描述BUG**
使用catserver作为服务端时，服务器玩家无法默认解锁阶段1，导致无法正常游玩，但在单人游戏中可以正常使用
**如何重现**
未知
**原本期望**
服务器中可以默认解锁阶段1

**截图**
![image](https://user-images.githubusercontent.com/56632587/174570074-9b32925f-d9c0-49c6-a937-d7098ccaef61.png)

**运行环境（请越详细越好）:**
 - 操作系统*：windows10LTSC 1809
 - 运行内存：24GB
 - Java版本：1.8.0_311
- 整合包版本*：1.5.6

**错误报告**
未发生崩溃
以下为玩家看到的错误
![JFPCKF 5D(KH7_)R4M8)%W](https://user-images.githubusercontent.com/56632587/174570765-8e606931-6420-43a2-9f01-a9b46713adb7.png)

以下为服务端latest.log
[latest.log](https://github.com/ET-Team/EnigTech2/files/8939291/latest.log)

**Comment by djp440** [comment]
经过验证发现，确实是CatServer的问题，如果使用作者为整合包附带的forge服务端，则没有上述问题发生，但仍希望作者能够使整合包兼容其他服务端

**Comment by dong031001** [comment]
无法支持，请转移至catserver repo。
