### ISSUE TITLE
[BUG]钨钢仍无法获得

### ISSUE THREAD

**Issue by Ult1mateNoob** [ET-Team/EnigTech2#633]
**描述BUG**
钨钢锭无法获得，解锁钨矿进度的逆银矿烧出来还是紫黑格子的“空部件“，钨钢矿石烧不了，它的粉只能用来合成铬锭
**如何重现**
游玩1.6.0/1.5.7
**原本期望**
若无此BUG，原本你期待发生什么？
逆银矿的粉烧出来获得钨锭或处理后获得钨钢/石榴石玫瑰下面的钨矿脉挖出来的是钨矿石并且可以处理出钨钢锭
**截图**
![1$5XEW$234MZH64J5~R(22X](https://user-images.githubusercontent.com/108606537/177032645-8a2ef8c7-605e-443e-be02-baf0fc3a70d3.png)
上为钨钢锭配方
![7BR(S4B 921OF0CF0S0UD1E](https://user-images.githubusercontent.com/108606537/177032652-b2433124-f7f3-499f-9915-d138b9fde335.png)
上为逆银矿烧出来的配方
![tungstenpowder](https://user-images.githubusercontent.com/108606537/177032712-833ec010-ba2c-4cff-9f3e-42f12f3ce316.png)
上为钨钢粉可以合成的奇怪配方

**运行环境（请越详细越好）:**
 - 操作系统*：win10 pro 20H2
 - 运行内存：32gb
 - Java版本：java8与java17sdk
- 整合包版本*：1.6.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
没有崩溃捏

**Comment by dong031001** [comment]
本地测试无问题，是使用的最新的安装包吗？有任何模组没有成功加载吗？进入游戏时有任何报错提示吗？

**Comment by Ult1mateNoob** [comment]
是使用的1.6.0的包拖进pcl，然后加了1.5.x的dlc包，还有一些自己加的mod，旅行者背包什么的，应该不影响吧？

**Comment by Ult1mateNoob** [comment]
使用的1.5.7和1.6.0的安装包拖进pcl自动装包的，两次都加了1.5.x的dlc，还有旅行者背包之类的mod，我明天试试不加额外mod

**Comment by Ult1mateNoob** [comment]
没有报错捏

**Comment by Ult1mateNoob** [comment]
又新开了一个包，新开的存档没问题，加载之前的存档会报缺失hyunium的盔甲套装，加载第一次报错崩溃，加载第二次就没事了，总之谢谢

**Comment by Ult1mateNoob** [comment]
终究还是坏档了捏QAQ
