### ISSUE TITLE
专家版多方块机械配方加载失败[BUG]

### ISSUE THREAD

**Issue by Young0718** [ET-Team/EnigTech2#644]
**描述BUG**
专家版多方块机械配方加载失败
解决方法：在 `crafttweaker\expert\vanilla\StageSix\removes.zs` 中的第111行尾，也就是 `<mekanism:teleportationcore>` 后加上一个半角逗号
![屏幕截图 2022-07-26 225113](https://user-images.githubusercontent.com/60529081/181038889-f3c5e6f8-aa7e-4b25-aeab-2a0921aa6475.png)

**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![屏幕截图 2022-07-26 225416](https://user-images.githubusercontent.com/60529081/181039349-cf597c0e-f929-4439-ba34-446070f2471c.png)
![屏幕截图 2022-07-26 225438](https://user-images.githubusercontent.com/60529081/181039357-67494133-81cf-4ac8-96cc-759bd7537f5d.png)

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：

- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
感谢反馈，如果能以PR形式会更加方便，再次感谢。
