### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bilibili12433014** [ET-Team/EnigTech2#646]
**描述BUG**
找不到镍矿，我和室友一起玩的，铝矿周围没有生成镍矿，已经开了很大个地图挖了近一个星期了
**如何重现**
用的1.6.0的服务器+客户端运行，没用更改任何配置
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![Uploading 图片.png…]()

**运行环境（请越详细越好）:**
 - 操作系统*：Win11
 - 运行内存：4096MB
 - Java版本：
- 整合包版本*：1.6

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
本地测试无问题，应该是阶段没到。

**Comment by dong031001** [comment]
![2022-08-04_20 21 47](https://user-images.githubusercontent.com/30747164/182845936-a99d9441-6b5e-4dd8-8254-36ffc6dce78e.png)
![2022-08-04_20 21 05](https://user-images.githubusercontent.com/30747164/182845968-023c3292-ee0c-439b-92dd-ef6a5d0da3e4.png)
![2022-08-04_20 21 10](https://user-images.githubusercontent.com/30747164/182846024-dc79aa1b-e946-45fd-aba8-9c06a1952219.png)
![2022-08-04_20 21 16](https://user-images.githubusercontent.com/30747164/182846082-87e1fea4-f7d2-40bf-9994-1ecda5e84247.png)
![2022-08-04_20 21 31](https://user-images.githubusercontent.com/30747164/182846134-5bb09726-3161-496d-9b60-f53c0669e2e9.png)
