### ISSUE TITLE
[BUG]服务器下木棍无法合成简易打火器

### ISSUE THREAD

**Issue by plumstarlzx** [ET-Team/EnigTech2#649]
**描述BUG**
简易打火器无法合成
**如何重现**
服务器下木棍无法合成简易打火器
本地单人合成正常
服务器使用1.6.1.1的服务器包
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![image](https://user-images.githubusercontent.com/110776787/183296785-4d196556-9b6d-42a2-a14e-e649e8c882ac.png)

**运行环境（请越详细越好）:**
 - 操作系统*：windows10
 - 运行内存：5G
 - Java版本：8
- 整合包版本*：1.6.1.1
- 服务器操作系统：Ubuntu 
- 服务器管理面板：MCSManager 9.5
- 服务器分配内存：4G
**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
服务端文件已经修复，感谢反馈
