### ISSUE TITLE
[BUG]关于简易流体蒸馏器无法用一些管道接收流体

### ISSUE THREAD

**Issue by Ex5261** [ET-Team/EnigTech2#650]
**描述BUG**
简易流体蒸馏器无法用末影接口的管道和液体转运器和热力的管道接收流体
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
![2022-08-16_15 19 34](https://user-images.githubusercontent.com/111341478/184822240-84f9bcb8-0b1c-48ef-b056-ca796280f7fb.png)
![2022-08-16_15 19 40](https://user-images.githubusercontent.com/111341478/184822251-3fb57e36-3b62-4fec-ab8e-6845e76efe53.png)
![2022-08-16_15 19 44](https://user-images.githubusercontent.com/111341478/184822255-9790a00c-0132-4150-90ce-176c63d0ef9c.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows10
 - 运行内存：8096MB
 - Java版本：jer1.8.0-341
- 整合包版本*：[EnigTech2-v1.6.1.1]

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
可以换用晶圆处理总成。
