### ISSUE TITLE
[其他]一阶末任务和2个模块化机械的建议

### ISSUE THREAD

**Issue by Yisenayan** [ET-Team/EnigTech2#656]
1.精灵工匠台与森流之石移至森流仪式任务前
有新玩家在不知道该仪式用于激活森流之石，另外仪式所需木门需要二阶段才能合成，虽然可以跑图找
2.移除守门者之仗与注造站任务
貌似根源更新后在任务流程中并没有什么用

3.圆晶圆晶处理总成造价昂贵，且速度差强人意，毕竟exu单方块机器自动化并不难做，而且可以放速度升级来提升速度
4.微装配机作为从前期到后期一直在使用的机器之一，是否可以增加速度升级来使后期大批量使用时减少等待时间

**Comment by dong031001** [comment]
@tuna5544

**Comment by dong031001** [comment]
针对第三点，EXU单方块机器在特定情况下会无法自动化输入输出。未来也会有改进速度的方案。
