### ISSUE TITLE
[BUG]github上1.6.1.1服务端scripts文件与1.6.1.1客户端文件不相同

### ISSUE THREAD

**Issue by Yisenayan** [ET-Team/EnigTech2#657]
**描述BUG**
github上1.6.1.1服务端scripts文件与1.6.1.1客户端文件不相同
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
下为专家模式阶段五六部分物品配方对比
![图片](https://user-images.githubusercontent.com/74770726/188786030-be779d41-54fc-4f56-aba6-f43f7b7293fc.png)
![图片](https://user-images.githubusercontent.com/74770726/188786067-a2258415-1588-41d1-a3c9-eb0b16850155.png)
![图片](https://user-images.githubusercontent.com/74770726/188786090-0fed446d-3b70-4301-8cae-889055990c29.png)
![图片](https://user-images.githubusercontent.com/74770726/188786113-86487cbb-d257-4dd9-b6ff-a97e3e3066e9.png)

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：1.6.1.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
服务端文件已经修复，感谢反馈
