### ISSUE TITLE
[BUG]服务端信素锭无法制作

### ISSUE THREAD

**Issue by QianZang1** [ET-Team/EnigTech2#661]
**描述BUG**
1.6.1.1服务器信素锭无法制作，显示缺少液体输入，单机正常
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Windows server 2016
 - 运行内存：
 - Java版本：
- 整合包版本*：服务端V1.6.1.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by Hydrogen897** [comment]
感觉最近关于服务端的BUG非常的多，建议小东把服务端也传个仓库

**Comment by zjscxiao** [comment]
看了下服务端EnigTech2-1.6.1.1-Server\scripts\crafttweaker\expert\mods\modularMachinery\blast_furnaces下recipes.zs中第74行位置配方和客户端不同，只有apple_juice可用，把客户端文件替换到服务端应该可以解决此问题
