### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by suchimo-2** [ET-Team/EnigTech2#662]
**描述BUG**
末影工作台的来泽尔石无法合成
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：服务端1.6.1.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by suchimo-2** [comment]
![1](https://user-images.githubusercontent.com/60172373/200243884-9ac6c7f4-7543-4544-b872-d6c15eaa54cc.png)
![2](https://user-images.githubusercontent.com/60172373/200243903-b55bdab5-1166-4057-966c-7e511ebad1e8.png)

**Comment by dong031001** [comment]
没有末影能量，建议看看这个模组的教程
