### ISSUE TITLE
[BUG]共两个，其中一个较严重

### ISSUE THREAD

**Issue by 1ChenFeng** [ET-Team/EnigTech2#664]
**描述BUG**
1.在末地使用意志之剑刷取恶魔意志，返回主世界后，偶尔会立即或在下次进入存档时造成魔能高炉高强合金配方丢失。暂时可以通过一次或多次重新加载游戏解决。
2.莫比乌斯燃料无法合成，在AE合成终端可显示出产物但无法取出，在工作台则完全不显示。
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10
 - 运行内存：16G
 - Java版本：
- 整合包版本*：1.6.11

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
2无法重现。你是否改变了贤者之石的模式？

**Comment by 1ChenFeng** [comment]
原因已找到
因模组上自行添加了JEIBees，并把原有的物品整理换成了物品分拣模组（Inventory Sorter），测试中发现是物品分拣（Inventory Sorter）所导致的。更换物品分拣的原因是，原有的物品整理，在多人联机的情况下会经常出现，背包卡物品即看上去整了但实际没整，表现为任意点拖物品会回弹至整理前，体验极差，故换成物品分拣

**Comment by 1ChenFeng** [comment]
您可以通过JEI快速填充配方，看一下是否可以进行合成。我将自行添加的模组禁用后，在工作台可以进行合成，但一打开合成终端，或者通过JEI快速填充后，又出现上述问题

**Comment by 1ChenFeng** [comment]
好吧，贤者之石切换一次模式之后就什么毛病也没有了
