### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CLoongStar** [ET-Team/EnigTech2#667]
**描述BUG**
1.6.1.1版本中，当我跳跃到箱子上时，人物会卡死，即无法移动和打开背包，但仍然可以与已经摆放的方块互动，此现象只有在完全退出minecraft重新进入后才会暂时消失。

**如何重现**
人物跳到箱子上

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 11
 - 运行内存：4G
 - Java版本：Java 8(8.0.331）
- 整合包版本*：1.6.1.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
1.12.2空气方块BUG
