### ISSUE TITLE
[BUG]dlc2崩溃

### ISSUE THREAD

**Issue by AviciiLove-Github** [ET-Team/EnigTech2#675]
**描述BUG**
在加入dlc2时崩溃
**如何重现**
加入dlc2的模组
**原本期望**
若无此BUG，原本你期待发生什么？
游戏正常启动
**截图**
![image](https://user-images.githubusercontent.com/105161439/232231341-ea751379-2828-494c-b2dd-3d2d4c9aa435.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows
 - 运行内存：8000MB
 - Java版本：jdk1.8.0_351
- 整合包版本*：1.6.1.1

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2023-04-15_22.55.34-client.txt](https://github.com/ET-Team/EnigTech2/files/11239818/crash-2023-04-15_22.55.34-client.txt)

**Comment by AviciiLove-Github** [comment]
解决方法：更换draconic additions的版本

**Comment by dong031001** [comment]
将在下个版本同步更新DLC包内模组版本

**Comment by dong031001** [comment]
#669
