### ISSUE TITLE
[其他] 暮色森林的拆解台仍能在空心矿山（中）的箱子中获得

### ISSUE THREAD

**Issue by SpCoGov** [ET-Team/EnigTech2#677]
尽管拆解台的配方被删除，但玩家依旧能从空心矿山（中）的宝箱中获得。

**Comment by SpCoGov** [comment]
参考https://www.mcmod.cn/item/9339.html和https://www.mcmod.cn/item/3851.html

**Comment by Gebardensprache** [comment]
事实上这个问题用Game Stage应该就能修，但没人知道发PR还有没有用了，也许小东在做其他的事

**Comment by SpCoGov** [comment]
> 事实上这个问题用Game Stage应该就能修，但没人知道发PR还有没有用了，也许小东在做其他的事

好吧
