### ISSUE TITLE
[BUG]1.6.1.1服务端启动时崩溃

### ISSUE THREAD

**Issue by Sunday40847** [ET-Team/EnigTech2#678]
**描述BUG**
服务端
**如何重现**
下载解压1.6.1.1server，打开start.bat

**截图**
<img width="734" alt="微信图片_20240118210719" src="https://github.com/ET-Team/EnigTech2/assets/86839110/0276a57f-a465-4761-a2de-3e2ba257612f">

**运行环境（请越详细越好）:**
 - 操作系统*：Win10
 - 运行内存：4G
 - Java版本：forge-1.12.2-14.23.5.2860
- 整合包版本*：1.6.1.1

**错误报告**
如上截图，没有错误报告文件

**Comment by dong031001** [comment]
java版本？

**Comment by Sunday40847** [comment]
> java版本？

我刚才查看了环境变量path，里面有好多java版本。不知道启动时用了哪个版本
然后我把它指定成用java8的javaw.exe启动，就可以正常运行了
我考虑疏漏了，抱歉打扰到各位作者🙏
